-- Canonical Rachna + Aavartan Event Business OS schema.
-- Event ID / projects is the spine. No legacy CRM layers.
create extension if not exists pgcrypto;
create sequence if not exists public.event_code_seq;

create table if not exists organizations(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,organization_id uuid references organizations(id) on delete set null,full_name text,role text default 'staff',created_at timestamptz not null default now());
create table if not exists customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,name text not null,phone text,whatsapp text,email text,notes text,created_at timestamptz not null default now());
create table if not exists inquiries(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid references customers(id) on delete set null,source text,status text not null default 'new',owner_id uuid references profiles(id) on delete set null,event_name text,event_date_bs text,venue text,guest_count integer,budget numeric,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists projects(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,customer_id uuid references customers(id) on delete set null,inquiry_id uuid references inquiries(id) on delete set null,name text not null,status text not null default 'planning',brand text,quoted_total numeric not null default 0,internal_cost numeric not null default 0,customer_advance numeric not null default 0,vendor_reserve numeric not null default 0,date_range_bs text,event_code text unique,created_at timestamptz not null default now());
create table if not exists event_functions(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,name text not null,event_date date,event_date_bs text,start_time time,venue text,guest_count integer,notes text);
create table if not exists services(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,brand text not null,name text not null,category text,base_price numeric not null default 0,internal_cost numeric not null default 0,active boolean not null default true);
create table if not exists project_services(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,service_id uuid references services(id) on delete set null,name text not null,customer_price numeric not null default 0,internal_cost numeric not null default 0,quantity numeric not null default 1);
create table if not exists vendors(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,name text not null,phone text,service_category text,area text,rate_guide text,reliability text default 'Medium',notes text,created_at timestamptz not null default now());
create table if not exists vendor_bookings(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,vendor_id uuid not null references vendors(id) on delete cascade,category text,requirement text,quantity numeric not null default 1,client_price numeric not null default 0,quoted_cost numeric not null default 0,advance_paid numeric not null default 0,final_paid numeric not null default 0,payable numeric not null default 0,status text not null default 'reserved',notes text);
create table if not exists team_members(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,name text not null,role text,phone text,email text,active boolean not null default true,created_at timestamptz not null default now());
create table if not exists project_team(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,team_member_id uuid not null references team_members(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,responsibility text,rate numeric not null default 0);
create table if not exists payments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,project_id uuid references projects(id) on delete cascade,direction text not null,party_type text not null,party_id uuid,amount numeric not null,payment_date date not null default current_date,method text,reference text,notes text,created_at timestamptz not null default now(),constraint payments_direction_valid check(direction in ('in','out')),constraint payments_amount_valid check(amount>0));
create table if not exists project_expenses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,project_id uuid references projects(id) on delete cascade,category text not null,description text not null,amount numeric not null,expense_date date not null default current_date,method text,notes text,created_at timestamptz not null default now(),constraint expense_amount_valid check(amount>0));
create table if not exists production_costs(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,brand text not null,category text not null,description text not null,quantity numeric not null default 1,unit_cost numeric not null default 0,notes text,created_at timestamptz not null default now());
create table if not exists quotations(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,version integer not null default 1,status text not null default 'draft',customer_total numeric not null default 0,internal_total numeric not null default 0,notes text,created_at timestamptz not null default now());
create table if not exists quotation_items(id uuid primary key default gen_random_uuid(),quotation_id uuid not null references quotations(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,service_id uuid references services(id) on delete set null,description text not null,quantity numeric not null default 1,customer_price numeric not null default 0,internal_cost numeric not null default 0);
create table if not exists aavartan_deliverables(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,deliverable text not null,status text not null default 'pending',due_date date,delivered_at timestamptz);
create table if not exists production_jobs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,brand text not null default 'Aavartan',job_type text not null,tracker_type text not null default 'photo',stage text not null default 'Received',title text not null,due_date date,assigned_to uuid references team_members(id) on delete set null,notes text,status text not null default 'pending',created_at timestamptz not null default now());
create table if not exists event_files(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,project_id uuid not null references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,name text not null,kind text not null default 'link',url text,notes text,created_at timestamptz not null default now());
create table if not exists reminders(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,project_id uuid references projects(id) on delete cascade,function_id uuid references event_functions(id) on delete set null,reminder_type text not null default 'general',title text not null,due_at timestamptz,priority text not null default 'normal',status text not null default 'open',notes text,created_at timestamptz not null default now());

alter table public.vendor_bookings add column if not exists category text;
alter table public.vendor_bookings add column if not exists requirement text;
alter table public.vendor_bookings add column if not exists quantity numeric not null default 1;
alter table public.vendor_bookings add column if not exists client_price numeric not null default 0;
alter table public.vendor_bookings add column if not exists payable numeric not null default 0;
alter table public.vendor_bookings add column if not exists notes text;
alter table public.production_jobs add column if not exists tracker_type text not null default 'photo';
alter table public.production_jobs add column if not exists status text not null default 'pending';

create or replace function public.my_org_id() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from public.profiles where id=auth.uid() $$;
revoke execute on function public.my_org_id() from anon; grant execute on function public.my_org_id() to authenticated;

create or replace function public.set_project_event_code() returns trigger language plpgsql set search_path=public as $$ begin if coalesce(trim(new.event_code),'')='' then new.event_code:='RCH-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.event_code_seq')::text,5,'0'); end if; return new; end $$;
drop trigger if exists trg_projects_event_code on public.projects;
drop trigger if exists set_project_event_code on public.projects;
create trigger set_project_event_code before insert on public.projects for each row execute function public.set_project_event_code();

create or replace function public.refresh_project_financials(p_project_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_org uuid; v_quote numeric:=0; v_cost numeric:=0; v_has_quote boolean:=false;
begin
 v_org:=public.my_org_id(); if v_org is null then raise exception 'No workspace'; end if;
 select exists(select 1 from quotations q where q.project_id=p_project_id and q.status<>'rejected') into v_has_quote;
 if v_has_quote then select coalesce(sum(i.customer_price*i.quantity),0),coalesce(sum(i.internal_cost*i.quantity),0) into v_quote,v_cost from quotation_items i join quotations q on q.id=i.quotation_id where q.project_id=p_project_id and q.status<>'rejected';
 else select coalesce(sum(customer_price*quantity),0),coalesce(sum(internal_cost*quantity),0) into v_quote,v_cost from project_services where project_id=p_project_id; end if;
 v_cost:=v_cost+coalesce((select sum(quoted_cost) from vendor_bookings where project_id=p_project_id),0)+coalesce((select sum(quantity*unit_cost) from production_costs where project_id=p_project_id),0)+coalesce((select sum(amount) from project_expenses where project_id=p_project_id),0)+coalesce((select sum(rate) from project_team where project_id=p_project_id),0);
 update projects set quoted_total=v_quote,internal_cost=v_cost where id=p_project_id and organization_id=v_org;
end $$;
revoke execute on function public.refresh_project_financials(uuid) from anon; grant execute on function public.refresh_project_financials(uuid) to authenticated;

create or replace function public.apply_customer_advance(p_project_id uuid,p_amount numeric,p_method text default null,p_reference text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_org uuid; v_total numeric; v_received numeric; v_customer uuid; v_inquiry uuid; v_required numeric; v_reserve numeric; v_booked boolean;
begin v_org:=public.my_org_id(); if v_org is null then raise exception 'No workspace'; end if; select quoted_total,customer_id,customer_advance,inquiry_id into v_total,v_customer,v_received,v_inquiry from projects where id=p_project_id and organization_id=v_org for update; if not found then raise exception 'Project not found'; end if; if coalesce(v_total,0)<=0 then raise exception 'Add a customer quotation before collecting a booking advance'; end if; if coalesce(p_amount,0)<=0 then raise exception 'Advance must be greater than zero'; end if; v_received:=coalesce(v_received,0)+p_amount; v_required:=v_total*.30; v_reserve:=v_received*.15; v_booked:=v_received>=v_required; insert into payments(organization_id,project_id,direction,party_type,party_id,amount,method,reference,notes) values(v_org,p_project_id,'in','customer',v_customer,p_amount,p_method,p_reference,'Customer advance'); update projects set customer_advance=v_received,vendor_reserve=v_reserve,status=case when v_booked then 'booked' else status end where id=p_project_id; if v_inquiry is not null then update inquiries set status=case when v_booked then 'booked' else 'awaiting_advance' end,updated_at=now() where id=v_inquiry and organization_id=v_org; end if; return jsonb_build_object('received',v_received,'required',v_required,'vendor_reserve',v_reserve,'booked',v_booked); end $$;
revoke execute on function public.apply_customer_advance(uuid,numeric,text,text) from anon; grant execute on function public.apply_customer_advance(uuid,numeric,text,text) to authenticated;

create or replace function public.apply_vendor_payment(p_vendor_booking_id uuid,p_amount numeric,p_method text default null,p_reference text default null,p_is_advance boolean default false) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_org uuid; v_project uuid; v_vendor uuid; v_cost numeric; v_adv numeric; v_final numeric;
begin v_org:=public.my_org_id(); if v_org is null then raise exception 'No workspace'; end if; if coalesce(p_amount,0)<=0 then raise exception 'Payment must be greater than zero'; end if; select vb.project_id,vb.vendor_id,vb.quoted_cost,vb.advance_paid,vb.final_paid into v_project,v_vendor,v_cost,v_adv,v_final from vendor_bookings vb join projects p on p.id=vb.project_id where vb.id=p_vendor_booking_id and p.organization_id=v_org for update; if not found then raise exception 'Vendor booking not found'; end if; if p_is_advance then v_adv:=coalesce(v_adv,0)+p_amount; else v_final:=coalesce(v_final,0)+p_amount; end if; if v_adv+v_final>coalesce(v_cost,0) then raise exception 'Vendor payment exceeds vendor cost'; end if; insert into payments(organization_id,project_id,direction,party_type,party_id,amount,method,reference,notes) values(v_org,v_project,'out','vendor',v_vendor,p_amount,p_method,p_reference,case when p_is_advance then 'Vendor advance' else 'Vendor final payment' end); update vendor_bookings set advance_paid=v_adv,final_paid=v_final,payable=greatest(v_cost-v_adv-v_final,0),status=case when v_adv+v_final>=v_cost and v_cost>0 then 'paid' else 'reserved' end where id=p_vendor_booking_id; perform refresh_project_financials(v_project); return jsonb_build_object('remaining',greatest(v_cost-v_adv-v_final,0)); end $$;
revoke execute on function public.apply_vendor_payment(uuid,numeric,text,text,boolean) from anon; grant execute on function public.apply_vendor_payment(uuid,numeric,text,text,boolean) to authenticated;

create or replace function public.save_project_service_scope(p_project_id uuid,p_rows jsonb default '[]'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_org uuid; v_count integer:=0;
begin v_org:=public.my_org_id(); if v_org is null then raise exception 'No workspace'; end if; if not exists(select 1 from projects where id=p_project_id and organization_id=v_org) then raise exception 'Project not found'; end if; delete from project_services where project_id=p_project_id; insert into project_services(project_id,function_id,service_id,name,customer_price,internal_cost,quantity) select p_project_id,r.function_id,r.service_id,r.name,coalesce(r.customer_price,0),coalesce(r.internal_cost,0),coalesce(r.quantity,1) from jsonb_to_recordset(coalesce(p_rows,'[]'::jsonb)) as r(function_id uuid,service_id uuid,name text,customer_price numeric,internal_cost numeric,quantity numeric); get diagnostics v_count=row_count; perform refresh_project_financials(p_project_id); return jsonb_build_object('project_id',p_project_id,'service_count',v_count); end $$;
revoke execute on function public.save_project_service_scope(uuid,jsonb) from anon; grant execute on function public.save_project_service_scope(uuid,jsonb) to authenticated;

create or replace function public.bootstrap_workspace(p_full_name text default null,p_org_name text default null) returns uuid language plpgsql security definer set search_path=public,auth as $$
declare v_uid uuid:=auth.uid(); v_org uuid;
begin if v_uid is null then raise exception 'Authentication required'; end if; select organization_id into v_org from profiles where id=v_uid; if v_org is null then insert into organizations(name) values(coalesce(nullif(trim(p_org_name),''),'Rachna Workspace')) returning id into v_org; insert into profiles(id,organization_id,full_name,role) values(v_uid,v_org,coalesce(nullif(trim(p_full_name),''),'Owner'),'owner') on conflict(id) do update set organization_id=excluded.organization_id,full_name=excluded.full_name,role='owner'; else update profiles set full_name=coalesce(nullif(trim(p_full_name),''),full_name) where id=v_uid; end if; if not exists(select 1 from vendors where organization_id=v_org) then insert into vendors(organization_id,name,service_category,reliability,notes) values(v_org,'Karan','Event decoration','High','Primary decoration vendor'); end if; insert into services(organization_id,brand,name,category,base_price,internal_cost) select v_org,x.brand,x.name,x.category,x.base_price,x.internal_cost from (values ('Rachna','Event decoration','Event management',0::numeric,0::numeric),('Rachna','Event coordination','Event management',0::numeric,0::numeric),('Rachna','Catering coordination','Event management',0::numeric,0::numeric),('Rachna','Mehendi','Event management',0::numeric,0::numeric),('Rachna','Makeup & beauty','Event management',0::numeric,0::numeric),('Rachna','Band / DJ / artists','Event management',0::numeric,0::numeric),('Rachna','Panche baja','Event management',0::numeric,0::numeric),('Rachna','Venue coordination','Event management',0::numeric,0::numeric),('Rachna','Wedding car / transport','Event management',0::numeric,0::numeric),('Aavartan','Aavartan Photo + Video','Photography + Video',0::numeric,0::numeric),('Aavartan','Candid coverage','Add-on',12000::numeric,0::numeric),('Aavartan','Cinematic coverage','Add-on',15000::numeric,0::numeric),('Aavartan','Drone','Add-on',8000::numeric,0::numeric),('Aavartan','Premium Karizma album','Add-on',10000::numeric,0::numeric),('Aavartan','Social media reels','Add-on',15000::numeric,0::numeric),('Aavartan','Additional photographer','Add-on',12000::numeric,0::numeric),('Aavartan','Additional videographer','Add-on',12000::numeric,0::numeric),('Aavartan','Pre-wedding','Add-on',25000::numeric,0::numeric),('Aavartan','Post-wedding','Add-on',25000::numeric,0::numeric),('Aavartan','Additional album','Add-on',5000::numeric,0::numeric),('Aavartan','Photo frame','Add-on',0::numeric,0::numeric)) as x(brand,name,category,base_price,internal_cost) where not exists(select 1 from services s where s.organization_id=v_org and s.brand=x.brand and s.name=x.name); return v_org; end $$;
revoke execute on function public.bootstrap_workspace(text,text) from anon; grant execute on function public.bootstrap_workspace(text,text) to authenticated;

-- RLS: one canonical workspace policy per table.
alter table organizations enable row level security; alter table profiles enable row level security; alter table customers enable row level security; alter table inquiries enable row level security; alter table projects enable row level security; alter table event_functions enable row level security; alter table services enable row level security; alter table project_services enable row level security; alter table vendors enable row level security; alter table vendor_bookings enable row level security; alter table team_members enable row level security; alter table project_team enable row level security; alter table payments enable row level security; alter table project_expenses enable row level security; alter table production_costs enable row level security; alter table quotations enable row level security; alter table quotation_items enable row level security; alter table aavartan_deliverables enable row level security; alter table production_jobs enable row level security; alter table event_files enable row level security; alter table reminders enable row level security;

-- Policies are managed by migrations in production. Keep schema safe for resets by using the same canonical organization/project predicates.
drop policy if exists "org members" on organizations; create policy "org members" on organizations for select using(id=my_org_id());
drop policy if exists "profiles own org" on profiles; create policy "profiles own org" on profiles for select using(id=auth.uid() or organization_id=my_org_id()); drop policy if exists "profile bootstrap only" on profiles; create policy "profile bootstrap only" on profiles for insert with check(id=auth.uid() and organization_id is null);
