(()=>{
'use strict';
const URL='https://awptvpxfzhqeawrpdczg.supabase.co';
const KEY='sb_publishable_4D7iA3OZGhalc6bzxtYgBw__jCUmOVq';
const sb=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const state={user:null,profile:null,org:null,connected:false,customers:[],inquiries:[],projects:[],functions:[],services:[],projectServices:[],vendors:[],vendorBookings:[],team:[],projectTeam:[],tasks:[],payments:[],expenses:[],quotations:[],quotationItems:[],productionCosts:[],deliverables:[],documents:[],marketing:[],error:null};
const ORG=['customers','inquiries','projects','services','vendors','tasks','payments','project_expenses','team_members','documents','marketing_leads'];
const money=n=>'NPR '+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const orgId=()=>{const id=state.profile?.organization_id;if(!id)throw Error('Workspace is not initialized. Sign in again.');return id};
async function run(p){const r=await p;if(r.error)throw r.error;return r.data}
async function profile(){if(!state.user)return;state.profile=await run(sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle());if(state.profile?.organization_id)state.org=await run(sb.from('organizations').select('*').eq('id',state.profile.organization_id).maybeSingle())}
async function bootstrap(){await run(sb.rpc('bootstrap_workspace',{p_full_name:state.user?.user_metadata?.full_name||state.user?.email?.split('@')[0]||'Owner',p_org_name:'Rachna Workspace'}));await profile()}
async function refresh(){if(!state.user)return state;if(!state.profile?.organization_id)await bootstrap();const qs=[sb.from('customers').select('*').order('created_at',{ascending:false}),sb.from('inquiries').select('*').order('updated_at',{ascending:false}),sb.from('projects').select('*').order('created_at',{ascending:false}),sb.from('event_functions').select('*').order('event_date'),sb.from('services').select('*').order('brand').order('name'),sb.from('project_services').select('*').order('name'),sb.from('vendors').select('*').order('name'),sb.from('vendor_bookings').select('*'),sb.from('team_members').select('*').order('name'),sb.from('project_team').select('*'),sb.from('tasks').select('*').order('due_date'),sb.from('payments').select('*').order('payment_date',{ascending:false}),sb.from('project_expenses').select('*').order('expense_date',{ascending:false}),sb.from('quotations').select('*').order('created_at',{ascending:false}),sb.from('quotation_items').select('*'),sb.from('production_costs').select('*').order('created_at',{ascending:false}),sb.from('aavartan_deliverables').select('*').order('due_date'),sb.from('documents').select('*').order('created_at',{ascending:false}),sb.from('marketing_leads').select('*').order('created_at',{ascending:false})];const rs=await Promise.all(qs);rs.forEach(r=>{if(r.error)throw r.error});[state.customers,state.inquiries,state.projects,state.functions,state.services,state.projectServices,state.vendors,state.vendorBookings,state.team,state.projectTeam,state.tasks,state.payments,state.expenses,state.quotations,state.quotationItems,state.productionCosts,state.deliverables,state.documents,state.marketing]=rs.map(r=>r.data||[]);return state}
async function init(){const r=await sb.auth.getSession();if(r.error)throw r.error;state.user=r.data.session?.user||null;state.connected=!!state.user;if(state.user){await profile();await refresh()}return state}
async function signIn(email,password){const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;state.user=r.data.user;state.connected=true;await profile();if(!state.profile?.organization_id)await bootstrap();await refresh();return state}
async function signUp(email,password,fullName){const r=await sb.auth.signUp({email,password,options:{data:{full_name:fullName||email.split('@')[0]}}});if(r.error)throw r.error;if(r.data.session){state.user=r.data.user;state.connected=true;await bootstrap();await refresh();}return r.data}
async function signOut(){await sb.auth.signOut();location.reload()}
async function insert(table,row){const data={...row};if(ORG.includes(table))data.organization_id=orgId();return run(sb.from(table).insert(data).select().single()).then(async d=>{await refresh();return d})}
async function update(table,id,row){return run(sb.from(table).update(row).eq('id',id).select().maybeSingle()).then(async d=>{await refresh();return d})}
async function remove(table,id){await run(sb.from(table).delete().eq('id',id));await refresh();return true}
async function createCustomer(x){if(!x.name?.trim())throw Error('Customer name is required');return insert('customers',{name:x.name.trim(),phone:x.phone||null,whatsapp:x.whatsapp||x.phone||null,email:x.email||null,notes:x.notes||null})}
async function createInquiry(x){if(!x.event_name?.trim())throw Error('Event name is required');if(!x.customer_name?.trim())throw Error('Customer name is required');let c=state.customers.find(v=>x.phone&&v.phone===x.phone.trim());if(!c)c=await createCustomer({name:x.customer_name,phone:x.phone,whatsapp:x.phone,email:x.email});return insert('inquiries',{customer_id:c.id,source:x.source||'Other',status:'new',owner_id:state.user.id,event_name:x.event_name.trim(),event_date_bs:x.event_date_bs||null,venue:x.venue||null,guest_count:x.guest_count?Number(x.guest_count):null,budget:x.budget?Number(x.budget):null,notes:x.notes||null})}
async function convertInquiry(id){const i=state.inquiries.find(x=>x.id===id);if(!i)throw Error('Inquiry not found');const old=state.projects.find(p=>p.inquiry_id===id);if(old)return old;const p=await insert('projects',{customer_id:i.customer_id,inquiry_id:id,name:i.event_name||'Event project',status:'planning',brand:'Rachna + Aavartan',date_range_bs:i.event_date_bs||null});let ad=null;try{ad=new DateConverter(i.event_date_bs).toAd()}catch{}await run(sb.from('event_functions').insert({project_id:p.id,name:i.event_name||'Event',event_date:ad?`${ad.year}-${String(ad.month).padStart(2,'0')}-${String(ad.date).padStart(2,'0')}`:null,event_date_bs:i.event_date_bs||null,venue:i.venue||null,guest_count:i.guest_count||null}));await run(sb.from('inquiries').update({status:'awaiting_advance'}).eq('id',id));await refresh();return state.projects.find(x=>x.id===p.id)||p}
async function insertProject(x){if(!x.name?.trim())throw Error('Project name is required');const p=await insert('projects',{customer_id:x.customer_id||null,name:x.name.trim(),status:'planning',brand:x.brand||'Rachna + Aavartan',date_range_bs:x.date_range_bs||null,inquiry_id:x.inquiry_id||null});if(x.function_name?.trim()){let ad=null;try{ad=new DateConverter(x.event_date_bs).toAd()}catch{}await run(sb.from('event_functions').insert({project_id:p.id,name:x.function_name.trim(),event_date:ad?`${ad.year}-${String(ad.month).padStart(2,'0')}-${String(ad.date).padStart(2,'0')}`:null,event_date_bs:x.event_date_bs||null,venue:x.venue||null,guest_count:x.guest_count?Number(x.guest_count):null}));await refresh()}return state.projects.find(v=>v.id===p.id)||p}
async function addFunction(projectId,x){let ad=null;try{ad=new DateConverter(x.event_date_bs).toAd()}catch{}return run(sb.from('event_functions').insert({...x,project_id:projectId,event_date:ad?`${ad.year}-${String(ad.month).padStart(2,'0')}-${String(ad.date).padStart(2,'0')}`:x.event_date||null,name:x.name.trim(),guest_count:x.guest_count?Number(x.guest_count):null}).select().single()).then(async d=>{await refresh();return d})}
async function createQuotation(projectId){const v=Math.max(0,...state.quotations.filter(q=>q.project_id===projectId).map(q=>Number(q.version)||0))+1;return insert('quotations',{project_id:projectId,version:v,status:'draft',customer_total:0,internal_total:0,notes:null})}
async function addQuoteItem(qid,x){return run(sb.from('quotation_items').insert({...x,quotation_id:qid,quantity:Number(x.quantity)||1,customer_price:Number(x.customer_price)||0,internal_cost:Number(x.internal_cost)||0}).select().single()).then(async d=>{const q=state.quotations.find(v=>v.id===qid);await refresh();if(q)await recalc(q.project_id);return d})}
async function recalc(projectId){if(projectId){await run(sb.rpc('refresh_project_financials',{p_project_id:projectId}));await refresh()}}
async function recordAdvance(pid,amount,method,reference){return run(sb.rpc('apply_customer_advance',{p_project_id:pid,p_amount:Number(amount),p_method:method||null,p_reference:reference||null})).then(async d=>{await refresh();return d})}
async function recordPayment(x){if(!(Number(x.amount)>0))throw Error('Amount must be greater than zero');return insert('payments',{project_id:x.project_id||null,direction:x.direction,party_type:x.party_type||'other',amount:Number(x.amount),payment_date:x.payment_date||today(),method:x.method||null,reference:x.reference||null,notes:x.notes||null})}
async function addVendorBooking(x){return insert('vendor_bookings',{...x,quoted_cost:Number(x.quoted_cost)||0,advance_paid:Number(x.advance_paid)||0,final_paid:Number(x.final_paid)||0})}
async function assignTeam(x){return insert('project_team',{...x,rate:Number(x.rate)||0})}
async function addProductionCost(x){return insert('production_costs',{...x,quantity:Number(x.quantity)||1,unit_cost:Number(x.unit_cost)||0})}
async function addDeliverable(x){return insert('aavartan_deliverables',x)}
async function saveServiceScope(projectId,packageName,addons,rachnaIds){const r=await run(sb.rpc('save_project_service_scope',{p_project_id:projectId,p_package:packageName,p_addons:addons||[],p_rachna_service_ids:rachnaIds||[]}));await refresh();return r}
window.RachnaAPI={sb,state,money,esc,init,refresh,signIn,signUp,signOut,bootstrap,createCustomer,createInquiry,convertInquiry,insertProject,addFunction,createQuotation,addQuoteItem,recalc,recordAdvance,recordPayment,addVendorBooking,assignTeam,addProductionCost,addDeliverable,saveServiceScope,insert,update,remove};
})();