(() => {
  const SUPABASE_URL='https://awptvpxfzhqeawrpdczg.supabase.co';
  const SUPABASE_KEY='sb_publishable_4D7iA3OZGhalc6bzxtYgBw__jCUmOVq';
  const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const state={user:null,profile:null,org:null,connected:false,customers:[],inquiries:[],projects:[],functions:[],services:[],vendors:[],vendorBookings:[],team:[],projectTeam:[],tasks:[],payments:[],expenses:[],quotations:[],quotationItems:[],productionCosts:[],deliverables:[],documents:[],marketing:[]};
  const money=n=>'NPR '+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0});
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const today=()=>new Date().toISOString().slice(0,10);
  const orgId=()=>{if(!state.profile?.organization_id)throw new Error('Workspace is not connected to an organization.');return state.profile.organization_id};
  async function q(p){const r=await p;if(r.error)throw r.error;return r.data}
  async function refresh(){if(!state.user||!state.profile?.organization_id)return state;const rs=await Promise.all([
    sb.from('customers').select('*').order('created_at',{ascending:false}),sb.from('inquiries').select('*').order('updated_at',{ascending:false}),sb.from('projects').select('*').order('created_at',{ascending:false}),sb.from('event_functions').select('*').order('event_date'),sb.from('services').select('*').eq('active',true).order('name'),sb.from('vendors').select('*').order('name'),sb.from('vendor_bookings').select('*'),sb.from('team_members').select('*').eq('active',true).order('name'),sb.from('project_team').select('*'),sb.from('tasks').select('*').order('due_date'),sb.from('payments').select('*').order('payment_date',{ascending:false}),sb.from('project_expenses').select('*').order('expense_date',{ascending:false}),sb.from('quotations').select('*').order('created_at',{ascending:false}),sb.from('quotation_items').select('*'),sb.from('production_costs').select('*'),sb.from('aavartan_deliverables').select('*'),sb.from('documents').select('*').order('created_at',{ascending:false}),sb.from('marketing_leads').select('*').order('created_at',{ascending:false})
  ]);for(const r of rs)if(r.error)throw r.error;[state.customers,state.inquiries,state.projects,state.functions,state.services,state.vendors,state.vendorBookings,state.team,state.projectTeam,state.tasks,state.payments,state.expenses,state.quotations,state.quotationItems,state.productionCosts,state.deliverables,state.documents,state.marketing]=rs.map(r=>r.data||[]);return state}
  async function profile(){state.profile=await q(sb.from('profiles').select('*').eq('id',state.user.id).maybeSingle());if(state.profile?.organization_id)state.org=await q(sb.from('organizations').select('*').eq('id',state.profile.organization_id).maybeSingle())}
  async function init(){const {data}=await sb.auth.getSession();state.user=data.session?.user||null;state.connected=!!state.user;if(state.user)await profile();return refresh()}
  async function signIn(email,password){const r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;state.user=r.data.user;state.connected=true;await profile();await refresh();return state}
  async function signUp(email,password,fullName,orgName){const r=await sb.auth.signUp({email,password});if(r.error)throw r.error;if(!r.data.user)throw Error('Signup did not create a user.');state.user=r.data.user;state.connected=!!r.data.session;if(!r.data.session)return{needsConfirmation:true};const org=await q(sb.from('organizations').insert({name:orgName||'Rachna Workspace'}).select().single());await q(sb.from('profiles').insert({id:state.user.id,organization_id:org.id,full_name:fullName||email,role:'owner'}));await q(sb.from('vendors').insert({organization_id:org.id,name:'Karan',service_category:'Decoration',notes:'Primary decoration vendor'}));const defaults=[['Rachna','Event Decoration','Decoration',50000,0],['Rachna','Full Event Planning','Planning',0,0],['Rachna','Venue Coordination','Coordination',0,0],['Rachna','Catering Coordination','Catering',0,0],['Rachna','Entertainment / Band Baja','Entertainment',0,0],['Aavartan','Photography','Photography',0,10000],['Aavartan','Videography','Videography',0,12000],['Aavartan','Cinematography','Cinematic',0,3000],['Aavartan','Drone Coverage','Production',4000,4000],['Aavartan','Karizma Album','Deliverable',10000,5000],['Aavartan','Wooden Pendrive','Deliverable',3000,3000],['Aavartan','Premium Frame','Deliverable',5000,5000],['Aavartan','Social Media Reels','Content',15000,0]];await q(sb.from('services').insert(defaults.map(x=>({organization_id:org.id,brand:x[0],name:x[1],category:x[2],base_price:x[3],internal_cost:x[4],active:true}))));await profile();await refresh();return state}
  async function signOut(){await sb.auth.signOut();location.reload()}
  async function insert(table,row){const data={...row};if(['customers','inquiries','projects','services','vendors','tasks','payments','project_expenses','team_members','documents','marketing_leads'].includes(table))data.organization_id=orgId();return q(sb.from(table).insert(data).select().single()).then(async o=>{await refresh();return o})}
  async function update(table,pk,row){await q(sb.from(table).update(row).eq('id',pk));await refresh()}
  async function createCustomer(x){return insert('customers',{name:x.name,phone:x.phone,whatsapp:x.whatsapp||x.phone,email:x.email||null,notes:x.notes||null})}
  async function createInquiry(x){let c=state.customers.find(a=>a.phone&&x.phone&&a.phone===x.phone);if(!c)c=await createCustomer({name:x.customer_name,phone:x.phone,whatsapp:x.whatsapp});return insert('inquiries',{customer_id:c.id,source:x.source||'Other',status:'new',event_name:x.event_name,event_date_bs:x.event_date_bs||null,venue:x.venue,guest_count:x.guest_count||null,budget:x.budget||null,notes:x.notes||null})}
  async function convertInquiry(inquiryId){const i=state.inquiries.find(x=>x.id===inquiryId);if(!i)throw Error('Inquiry not found');const p=await insert('projects',{customer_id:i.customer_id,inquiry_id:i.id,name:i.event_name||'New Event Project',status:'planning',brand:'Rachna + Aavartan',date_range_bs:i.event_date_bs||null});let ad=null;try{ad=i.event_date_bs&&window.DateConverter?new window.DateConverter(i.event_date_bs).toAd():null}catch{}await q(sb.from('event_functions').insert({project_id:p.id,name:i.event_name||'Event',event_date:ad?`${ad.year}-${String(ad.month).padStart(2,'0')}-${String(ad.date).padStart(2,'0')}`:null,event_date_bs:i.event_date_bs||null,venue:i.venue||null,guest_count:i.guest_count||null}));await update('inquiries',inquiryId,{status:'awaiting_advance'});return state.projects.find(x=>x.id===p.id)||p}
  async function addFunction(projectId,x){return q(sb.from('event_functions').insert({...x,project_id:projectId}).select().single()).then(async r=>{await refresh();return r})}
  async function addVendor(x){return insert('vendors',{name:x.name,phone:x.phone,service_category:x.category,area:x.area||null,rate_guide:x.rate_guide||null,reliability:x.reliability||'Medium',notes:x.notes})}
  async function addTeam(x){return insert('team_members',{name:x.name,role:x.role,phone:x.phone,email:x.email,active:true})}
  async function addTask(x){return insert('tasks',{project_id:x.project_id||null,function_id:x.function_id||null,title:x.title,assignee_id:x.assignee_id||null,due_date:x.due_date||null,status:x.status||'todo'})}
  async function updateTask(id,row){return update('tasks',id,row)}
  async function recordPayment(x){return insert('payments',{project_id:x.project_id||null,direction:x.direction,party_type:x.party_type||'customer',party_id:x.party_id||null,amount:Number(x.amount)||0,payment_date:x.payment_date||today(),method:x.method||null,reference:x.reference||null,notes:x.notes||null})}
  async function recordExpense(x){return insert('project_expenses',{project_id:x.project_id||null,category:x.category,description:x.description,amount:Number(x.amount)||0,expense_date:x.expense_date||today(),method:x.method||null,notes:x.notes||null})}
  async function recordAdvance(projectId,amount,method,reference){const n=Number(amount);if(!(n>0))throw Error('Enter a valid advance');const data=await q(sb.rpc('apply_customer_advance',{p_project_id:projectId,p_amount:n,p_method:method||null,p_reference:reference||null}));await refresh();return{booked:Boolean(data.booked),reserve:Number(data.vendor_reserve||0),received:Number(data.received||0),required:Number(data.required||0)}}
  async function addVendorBooking(x){const r=await q(sb.from('vendor_bookings').insert({...x}).select().single());await refresh();return r}
  async function updateVendorBooking(id,row){await q(sb.from('vendor_bookings').update(row).eq('id',id));await refresh()}
  async function createQuotation(projectId){const vs=state.quotations.filter(q=>q.project_id===projectId),v=(vs.reduce((m,x)=>Math.max(m,x.version||1),0)||0)+1;return insert('quotations',{project_id:projectId,version:v,status:'draft',customer_total:0,internal_total:0,notes:null})}
  async function addQuoteItem(quotationId,x){await q(sb.from('quotation_items').insert({...x,quotation_id:quotationId}));const qrow=state.quotations.find(q=>q.id===quotationId);const items=state.quotationItems.filter(i=>i.quotation_id===quotationId).concat([{...x}]);const total=items.reduce((s,i)=>s+Number(i.customer_price||0)*Number(i.quantity||1),0),cost=items.reduce((s,i)=>s+Number(i.internal_cost||0)*Number(i.quantity||1),0);if(qrow){await q(sb.from('quotations').update({customer_total:total,internal_total:cost}).eq('id',quotationId));await q(sb.from('projects').update({quoted_total:total,internal_cost:cost}).eq('id',qrow.project_id))}await refresh()}
  async function updateQuotation(id,row){return update('quotations',id,row)}
  async function addProductionCost(x){const r=await insert('production_costs',{project_id:x.project_id,function_id:x.function_id||null,brand:x.brand,category:x.category,description:x.description,quantity:Number(x.quantity)||1,unit_cost:Number(x.unit_cost)||0,notes:x.notes||null});return r}
  async function addDeliverable(x){return q(sb.from('aavartan_deliverables').insert({...x,project_id:x.project_id}).select().single()).then(async r=>{await refresh();return r})}
  async function updateDeliverable(id,row){await q(sb.from('aavartan_deliverables').update(row).eq('id',id));await refresh()}
  async function addMarketing(x){return insert('marketing_leads',x)}
  async function addService(x){return insert('services',{brand:x.brand,name:x.name,category:x.category,base_price:Number(x.base_price)||0,internal_cost:Number(x.internal_cost)||0,active:true})}
  window.RachnaAPI={sb,state,init,refresh,signIn,signUp,signOut,createCustomer,createInquiry,convertInquiry,addFunction,addService,addVendor,addTeam,addTask,updateTask,recordPayment,recordExpense,addVendorBooking,updateVendorBooking,recordAdvance,createQuotation,addQuoteItem,updateQuotation,addProductionCost,addDeliverable,updateDeliverable,addMarketing,update,money,esc};
})();