(() => {
  const A=window.RachnaAPI;
  const $=s=>document.querySelector(s);
  const esc=A.esc,money=A.money;
  const MONTHS=['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'];
  const CORE={name:'Aavartan Photo + Video',price:45000};
  const ADDONS=[['Candid coverage',12000],['Cinematic coverage',15000],['Drone',8000],['Premium Karizma album',10000],['Social media reels',15000],['Additional photographer',12000],['Additional videographer',12000],['Pre-wedding',25000],['Post-wedding',25000],['Additional album',5000]];
  const RACHNA=['Decoration / stage design','Venue coordination','Catering coordination','Makeup & beauty','Mehendi','Band / DJ / artists','Wedding car / transport','Panche baja','Event coordination'];
  const STATUS={new:'New',contacted:'Contacted',qualified:'Qualified',quote_sent:'Quote sent',negotiation:'Negotiation',awaiting_advance:'Awaiting advance',booked:'Booked',lost:'Lost',planning:'Planning',in_progress:'In progress',completed:'Completed',todo:'To do',done:'Done',pending:'Pending',delivered:'Delivered'};
  let page='home',pid=null,tab='overview',query='';
  A.remove=async(table,id)=>{const r=await A.sb.from(table).delete().eq('id',id);if(r.error)throw r.error;await A.refresh();return true};
  A.patch=async(table,id,row)=>{const r=await A.sb.from(table).update(row).eq('id',id).select().maybeSingle();if(r.error)throw r.error;await A.refresh();return r.data};
  A.addRow=async(table,row,org=true)=>{const data={...row};if(org&&['customers','inquiries','projects','services','vendors','tasks','payments','project_expenses','team_members','documents','marketing_leads'].includes(table))data.organization_id=A.state.profile?.organization_id;const r=await A.sb.from(table).insert(data).select().single();if(r.error)throw r.error;await A.refresh();return r.data};
  function toast(m,bad=false){const t=$('#toast');t.textContent=m;t.className='toast show '+(bad?'error':'');clearTimeout(window.__ft);window.__ft=setTimeout(()=>t.className='toast',3000)}
  function close(){const b=$('#backdrop');if(b)b.classList.remove('show')}
  function modal(title,body,actions=''){ $('#modal').innerHTML='<div class="modal-head"><div><div class="eyebrow">Rachna OS</div><h2>'+title+'</h2></div><button class="close-btn" onclick="window.__closeFix()">×</button></div><div class="modal-body">'+body+'</div><div class="modal-foot"><button class="btn" onclick="window.__closeFix()">Cancel</button>'+actions+'</div>';$('#backdrop').classList.add('show') }
  window.__closeFix=close;
  function field(label,id,type='text',value='',extra=''){return '<div class="field"><label>'+esc(label)+'</label><input id="'+id+'" type="'+type+'" value="'+esc(value??'')+'" '+extra+'></div>'}
  function area(label,id,value=''){return '<div class="field full"><label>'+esc(label)+'</label><textarea id="'+id+'">'+esc(value??'')+'</textarea></div>'}
  function select(label,id,opts,value=''){return '<div class="field"><label>'+esc(label)+'</label><select id="'+id+'">'+opts.map(o=>{const v=Array.isArray(o)?o[0]:o,l=Array.isArray(o)?o[1]:o;return '<option value="'+esc(v)+'" '+(String(v)===String(value)?'selected':'')+'>'+esc(l)+'</option>'}).join('')+'</select></div>'}
  function C(){return window.DateConverter||null}
  function bs2ad(v){try{const X=C();return X&&v?new X(v).toAd():null}catch{return null}}
  function ad2bs(v){try{const X=C();return X&&v?new X(v).toBs():null}catch{return null}}
  function todayBS(){return ad2bs(new Date().toISOString().slice(0,10))||{year:2083,month:6,date:18}}
  function validDays(y,m){const r=[];const X=C();if(X){for(let d=1;d<=32;d++){try{new X(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`).toAd();r.push(d)}catch{}}}return r.length?r:Array.from({length:32},(_,i)=>i+1)}
  function dateField(label,key,value=''){let p=todayBS();if(/^\d{4}-\d{2}-\d{2}$/.test(value)&&bs2ad(value)){const z=value.split('-').map(Number);p={year:z[0],month:z[1],date:z[2]}}const ys=Array.from({length:25},(_,i)=>2075+i),ds=validDays(p.year,p.month),d=ds.includes(p.date)?p.date:ds[ds.length-1];return '<div class="field full"><label>'+esc(label)+' · Bikram Sambat</label><div class="date-grid"><select id="'+key+'Y" onchange="window.__syncDate(\''+key+'\')">'+ys.map(y=>`<option value="${y}" ${y===p.year?'selected':''}>${y}</option>`).join('')+'</select><select id="'+key+'M" onchange="window.__syncDate(\''+key+'\')">'+MONTHS.map((m,i)=>`<option value="${i+1}" ${i+1===p.month?'selected':''}>${m}</option>`).join('')+'</select><select id="'+key+'D" onchange="window.__syncDate(\''+key+'\')">'+ds.map(x=>`<option value="${x}" ${x===d?'selected':''}>${x}</option>`).join('')+'</select></div><input type="hidden" id="'+key+'BS" value="'+esc(value||`${p.year}-${String(p.month).padStart(2,'0')}-${String(d).padStart(2,'0')}`)+'"><div id="'+key+'AD" class="date-preview"></div><small class="muted">Choose BS year, month and day. AD is generated automatically.</small></div>'}
  window.__syncDate=k=>{const y=+$('#'+k+'Y').value,m=+$('#'+k+'M').value,ds=validDays(y,m),old=+$('#'+k+'D').value,d=ds.includes(old)?old:ds[ds.length-1];$('#'+k+'D').innerHTML=ds.map(x=>`<option value="${x}" ${x===d?'selected':''}>${x}</option>`).join('');const bs=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;$('#'+k+'BS').value=bs;const a=bs2ad(bs);$('#'+k+'AD').textContent=a?`AD ${String(a.date).padStart(2,'0')} ${MONTHS[a.month-1]} ${a.year}`:'Select a valid BS date'};
  function primeDate(k){setTimeout(()=>window.__syncDate(k),0)}
  function badge(v){let c=/booked|completed|done|delivered|paid/i.test(v)?'green':/new|planning|pending|negotiation|awaiting|qualified|contacted|quote_sent|todo|in_progress/i.test(v)?'amber':'gold';return '<span class="tag '+c+'">'+esc(STATUS[v]||v||'—')+'</span>'}
  function head(e,t,s,a=''){return '<div class="page-head"><div><div class="eyebrow">'+esc(e)+'</div><h1>'+t+'</h1><p>'+s+'</p></div><div class="action-row">'+a+'</div></div>'}
  function kpi(l,v,f){return '<div class="card kpi"><small>'+esc(l)+'</small><strong>'+v+'</strong><span>'+esc(f)+'</span></div>'}
  function empty(t,s='Nothing here yet.'){return '<div class="empty-state"><strong>'+esc(t)+'</strong><span>'+esc(s)+'</span></div>'}
  function table(headers,rows){return '<div class="card table-wrap"><table><thead><tr>'+headers.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.join(''):'<tr><td colspan="'+headers.length+'">'+empty('No records')+'</td></tr>')+'</tbody></table></div>'}
  const nav=[['home','Home'],['inquiries','Inquiries'],['projects','Projects'],['calendar','Calendar'],['money','Money'],['settings','Settings']];
  function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#crumb').textContent=pid?'Project':(nav.find(x=>x[0]===page)||nav[0])[1];$('#page').innerHTML=pid?project():({home,inquiries,projects,calendar,money:moneyPage,settings}[page]||home)()}
  function go(p){page=p;pid=null;tab='overview';render()} window.go=go;
  function home(){const s=A.state,open=s.inquiries.filter(x=>!['booked','lost'].includes(x.status)).length,booked=s.projects.filter(x=>x.status==='booked').length,inc=s.payments.filter(x=>x.direction==='in').reduce((a,x)=>a+Number(x.amount||0),0),next=s.functions.filter(x=>x.event_date).slice().sort((a,b)=>a.event_date.localeCompare(b.event_date)).slice(0,5);return head('Rachna + Aavartan','Event command centre','One simple workflow for the whole company.','<button class="btn" onclick="newInquiry()">New inquiry</button><button class="btn primary" onclick="newProject()">New project</button>')+'<div class="grid four-col">'+kpi('Open inquiries',open,'Leads in progress')+kpi('Booked projects',booked,'30% advance confirmed')+kpi('Cash received',money(inc),'Recorded incoming')+kpi('Upcoming functions',next.length,'Scheduled events')+'</div><div class="card how"><div><div class="eyebrow">HOW TO USE IT</div><h2>One wedding = one project.</h2><p>Start with the inquiry. Create one project for the wedding. Add every function, then choose Aavartan Photo + Video as the core and tick optional add-ons. Add Rachna services only when needed. Then create the quote and record the 30% advance.</p></div><div class="flow"><div>1<small>Inquiry</small></div><span>→</span><div>2<small>Project</small></div><span>→</span><div>3<small>Services</small></div><span>→</span><div>4<small>Quote</small></div><span>→</span><div>5<small>30% advance</small></div><span>→</span><div>6<small>Booked</small></div></div></div><div class="grid two-col"><div class="card"><div class="section-title"><h2>Upcoming functions</h2><button class="btn" onclick="go(\'calendar\')">Calendar</button></div>'+(next.length?next.map(f=>'<div class="list-row"><div><b>'+esc(f.name)+'</b><div class="muted">'+esc(f.event_date_bs||'')+' · '+esc(f.venue||'Venue TBC')+'</div></div><span class="tag">'+esc(f.guest_count||0)+' guests</span></div>').join(''):empty('No upcoming functions'))+'</div><div class="card"><div class="eyebrow">AAVARTAN CORE</div><h2>Photography + Videography</h2><p>Always treated as a single core service. Everything else is an optional add-on.</p><div class="priority-line"><b>Core starting price</b><span>'+money(CORE.price)+'</span></div></div></div>'}
  function inquiries(){const rows=A.state.inquiries.map(i=>{const c=A.state.customers.find(x=>x.id===i.customer_id);return '<tr><td><b>'+esc(i.event_name||'Untitled')+'</b><div class="muted">'+esc(i.event_date_bs||'Date TBC')+'</div></td><td>'+esc(c?.name||'—')+'<div class="muted">'+esc(c?.phone||'')+'</div></td><td>'+esc(i.venue||'Venue TBC')+'</td><td>'+badge(i.status)+'</td><td><button class="btn" onclick="editInquiry(\''+i.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'inquiries\',\''+i.id+'\')">Delete</button></td></tr>'});return head('Sales','Inquiries','Every new lead starts here.','<button class="btn primary" onclick="newInquiry()">New inquiry</button>')+table(['Event','Customer','Venue','Stage',''],rows)}
  function projects(){const rows=A.state.projects.filter(p=>!query||p.name.toLowerCase().includes(query.toLowerCase())).map(p=>{const c=A.state.customers.find(x=>x.id===p.customer_id);return '<tr><td><b>'+esc(p.name)+'</b><div class="muted">'+esc(p.date_range_bs||'')+'</div></td><td>'+esc(c?.name||'—')+'</td><td>'+esc(p.brand||'—')+'</td><td>'+money(p.quoted_total)+'</td><td>'+money(p.customer_advance)+'</td><td>'+badge(p.status)+'</td><td><button class="btn" onclick="openP(\''+p.id+'\')">Open</button><button class="btn" onclick="editProject(\''+p.id+'\')">Edit</button><button class="btn danger" onclick="deleteProject(\''+p.id+'\')">Delete</button></td></tr>'});return head('Production','Projects','One master project per wedding or event.','<input class="search" placeholder="Search" value="'+esc(query)+'" oninput="query=this.value;render()"><button class="btn primary" onclick="newProject()">New project</button>')+table(['Project','Customer','Brand','Quoted','Advance','Status',''],rows)}
  function calendar(){const fs=A.state.functions.filter(f=>f.event_date).slice().sort((a,b)=>a.event_date.localeCompare(b.event_date));return head('Planning','Calendar','BS is the primary date. AD is shown automatically.','<button class="btn primary" onclick="quickFunction()">Add function</button>')+'<div class="calendar-list">'+(fs.length?fs.map(f=>{const p=A.state.projects.find(x=>x.id===f.project_id);return '<div class="card calendar-card"><div class="calendar-date"><b>'+esc(f.event_date_bs||'—')+'</b><small>'+esc(f.event_date||'')+'</small></div><div><h3>'+esc(f.name)+'</h3><p>'+esc(p?.name||'Project')+' · '+esc(f.venue||'Venue TBC')+'</p><div class="muted">'+esc(f.guest_count||0)+' guests</div></div><button class="btn" onclick="openP(\''+f.project_id+'\')">Open</button></div>'}).join(''):empty('No dates yet'))+'</div>'}
  function moneyPage(){const ins=A.state.payments.filter(x=>x.direction==='in').reduce((a,x)=>a+Number(x.amount||0),0),out=A.state.payments.filter(x=>x.direction==='out').reduce((a,x)=>a+Number(x.amount||0),0);return head('Finance','Money','Actual customer receipts and outgoing payments.','<button class="btn primary" onclick="globalPayment()">Record payment</button>')+'<div class="grid three-col">'+kpi('Cash in',money(ins),'Incoming')+kpi('Cash out',money(out),'Outgoing')+kpi('Net cash',money(ins-out),'Recorded only')+'</div>'+table(['Date','Project','Direction','Amount','Method',''],A.state.payments.slice(0,40).map(x=>'<tr><td>'+esc(x.payment_date||'—')+'</td><td>'+esc(A.state.projects.find(p=>p.id===x.project_id)?.name||'—')+'</td><td>'+badge(x.direction)+'</td><td>'+money(x.amount)+'</td><td>'+esc(x.method||'—')+'</td><td><button class="btn" onclick="editPayment(\''+x.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'payments\',\''+x.id+'\')">Delete</button></td></tr>'))}
  function settings(){return head('Workspace','Settings','Master lists and company rules.','<button class="btn" onclick="authFix()">Account</button>')+'<div class="grid two-col"><div class="card"><div class="eyebrow">BUSINESS RULES</div><h2>Rachna</h2><p>Event planning + management. Decoration, venue, catering, artists, transport and coordination are handled inside the same project.</p><h2>Aavartan</h2><p>Photography + Videography are one core service. Other production options are checkbox add-ons.</p><h2>Booking</h2><p>Customer advance must reach 30% of the quoted total before the project is marked booked.</p></div><div class="card"><div class="section-title"><h2>Master data</h2></div><button class="btn" onclick="customersManager()">Customers</button><button class="btn" onclick="vendorsManager()">Vendors</button><button class="btn" onclick="teamManager()">Team</button><button class="btn" onclick="servicesManager()">Services</button></div></div>'}
  function openP(id){pid=id;tab='overview';render()} window.openP=openP;
  function project(){const p=A.state.projects.find(x=>x.id===pid);if(!p)return projects();const c=A.state.customers.find(x=>x.id===p.customer_id),fs=A.state.functions.filter(x=>x.project_id===p.id),ps=A.state.projectServices.filter(x=>x.project_id===p.id),vb=A.state.vendorBookings.filter(x=>x.project_id===p.id),pt=A.state.projectTeam.filter(x=>x.project_id===p.id),ts=A.state.tasks.filter(x=>x.project_id===p.id),pay=A.state.payments.filter(x=>x.project_id===p.id),pc=A.state.productionCosts.filter(x=>x.project_id===p.id),ds=A.state.deliverables.filter(x=>x.project_id===p.id),qs=A.state.quotations.filter(x=>x.project_id===p.id);const views={overview:()=>overview(p,c,fs,ps,ts),functions:()=>functionsView(p,fs),services:()=>servicesView(p,ps),quote:()=>quoteView(p,qs),operations:()=>operationsView(p,vb,pt,pc),money:()=>projectMoney(p,pay),delivery:()=>deliveryView(p,ds)};const tabs=[['overview','Overview'],['functions','Functions'],['services','Services'],['quote','Quote'],['operations','Operations'],['money','Money'],['delivery','Delivery']];return head('Project',esc(p.name),esc(c?.name||'Customer')+' · '+esc(p.brand||'Rachna + Aavartan'),'<button class="btn" onclick="go(\'projects\')">Back</button><button class="btn" onclick="editProject(\''+p.id+'\')">Edit</button><button class="btn primary" onclick="openAdvance(\''+p.id+'\')">30% advance</button>')+'<div class="project-summary"><div><span>Quoted</span><b>'+money(p.quoted_total)+'</b></div><div><span>Advance</span><b>'+money(p.customer_advance)+'</b></div><div><span>Due</span><b>'+money(Math.max(0,Number(p.quoted_total||0)-Number(p.customer_advance||0)))+'</b></div></div><div class="subnav">'+tabs.map(t=>`<button class="subnav-btn ${tab===t[0]?'active':''}" onclick="tab='${t[0]}';render()">${t[1]}</button>`).join('')+'</div>'+views[tab]();}
  function overview(p,c,fs,ps,ts){const required=Number(p.quoted_total||0)*.3,ok=Number(p.customer_advance||0)>=required&&required>0;return '<div class="grid four-col">'+kpi('Functions',fs.length,'Events in project')+kpi('Services',ps.length,'Selected lines')+kpi('Tasks open',ts.filter(x=>x.status!=='done').length,'Pending work')+kpi('Booking',ok?'Confirmed':'Not booked','30% rule')+'</div><div class="grid two-col"><div class="card"><div class="eyebrow">PROJECT</div><h2>'+esc(p.name)+'</h2><div class="detail-list"><div><span>Customer</span><b>'+esc(c?.name||'—')+'</b></div><div><span>Phone</span><b>'+esc(c?.phone||'—')+'</b></div><div><span>Date range</span><b>'+esc(p.date_range_bs||'—')+'</b></div></div></div><div class="card"><div class="eyebrow">BOOKING</div><h2>'+ (ok?'Booked':'Awaiting advance')+'</h2><p>Required: '+money(required)+' · Received: '+money(p.customer_advance)+'</p></div></div>'}
  function functionsView(p,fs){return '<div class="section-bar"><div><h2>Functions</h2><p>Add Mehendi, Haldi, Engagement, Wedding, Reception or any custom function.</p></div><button class="btn primary" onclick="newFunction(\''+p.id+'\')">Add function</button></div><div class="function-grid">'+(fs.length?fs.map(f=>'<div class="card function-card"><div class="eyebrow">FUNCTION</div><h3>'+esc(f.name)+'</h3><b>'+esc(f.event_date_bs||'Date TBC')+'</b><small>'+esc(f.event_date||'')+'</small><small>'+esc(f.venue||'Venue TBC')+' · '+esc(f.guest_count||0)+' guests</small><div><button class="btn" onclick="editFunction(\''+f.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'event_functions\',\''+f.id+'\')">Delete</button></div></div>').join(''):empty('No functions yet','Add each event date separately.'))+'</div>'}
  function servicesView(p,ps){const total=ps.reduce((a,x)=>a+Number(x.customer_price||0)*Number(x.quantity||1),0);return '<div class="section-bar"><div><h2>Services</h2><p>Choose the core service and optional checkboxes. You can edit every selected line.</p></div><button class="btn primary" onclick="servicePicker(\''+p.id+'\')">Choose services</button></div><div class="card feature-card"><div><div class="eyebrow">AAVARTAN · CORE</div><h2>Photography + Videography</h2><p>One service, always together.</p></div><b>'+money(CORE.price)+'</b></div><div class="card"><div class="section-title"><h2>Selected lines</h2><b>'+money(total)+'</b></div>'+(ps.length?ps.map(x=>'<div class="service-row"><div><b>'+esc(x.name||'Service')+'</b><div class="muted">Qty '+esc(x.quantity||1)+' · '+esc(x.internal_cost||0)+' internal</div></div><div><b>'+money(Number(x.customer_price||0)*Number(x.quantity||1))+'</b><button class="btn" onclick="editProjectService(\''+x.id+'\')">Edit</button><button class="btn danger" onclick="delProjectService(\''+x.id+'\',\''+p.id+'\')">Delete</button></div></div>').join(''):empty('No services selected','Start with Aavartan Photo + Video.'))+'</div>'}
  function quoteView(p,qs){const q=[...qs].filter(x=>x.status!=='rejected').sort((a,b)=>Number(b.version)-Number(a.version))[0];return '<div class="section-bar"><div><h2>Quotation</h2><p>Create a new version whenever pricing changes.</p></div><button class="btn primary" onclick="newQuote(\''+p.id+'\')">New quotation</button></div>'+(q?'<div class="card quote-card"><div><div class="eyebrow">VERSION '+esc(q.version)+'</div><h2>'+badge(q.status)+'</h2><p>Total: <b>'+money(q.customer_total)+'</b></p></div><button class="btn" onclick="openQuote(\''+q.id+'\')">Open</button></div>':empty('No quotation yet','Create version 1 after choosing services.'))}
  function operationsView(p,vb,pt,pc){return '<div class="grid two-col"><div class="card"><div class="section-bar"><div><h2>Vendors</h2><p>Internal vendor costs stay private.</p></div><button class="btn" onclick="vendorBooking(\''+p.id+'\')">Add vendor</button></div>'+ (vb.length?vb.map(v=>'<div class="list-row"><div><b>'+esc(A.state.vendors.find(x=>x.id===v.vendor_id)?.name||'Vendor')+'</b><div class="muted">'+esc(A.state.functions.find(x=>x.id===v.function_id)?.name||'General')+'</div></div><div><b>'+money(v.quoted_cost)+'</b><button class="btn" onclick="editVendorBooking(\''+v.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'vendor_bookings\',\''+v.id+'\')">Delete</button></div></div>').join(''):empty('No vendor bookings'))+'</div><div class="card"><div class="section-bar"><div><h2>Team</h2></div><button class="btn" onclick="teamAssign(\''+p.id+'\')">Assign</button></div>'+(pt.length?pt.map(x=>'<div class="list-row"><div><b>'+esc(A.state.team.find(t=>t.id===x.team_member_id)?.name||'Team')+'</b><div class="muted">'+esc(A.state.team.find(t=>t.id===x.team_member_id)?.role||'')+'</div></div><div><b>'+money(x.rate)+'</b><button class="btn danger" onclick="delRow(\'project_team\',\''+x.id+'\')">Delete</button></div></div>').join(''):empty('No team assigned'))+'</div></div><div class="card" style="margin-top:15px"><div class="section-bar"><div><h2>Production costs</h2><p>Aavartan operational costs.</p></div><button class="btn" onclick="newProductionCost(\''+p.id+'\')">Add cost</button></div>'+(pc.length?pc.map(x=>'<div class="list-row"><div><b>'+esc(x.description)+'</b><div class="muted">'+esc(x.category||'Other')+'</div></div><div><b>'+money(Number(x.quantity||1)*Number(x.unit_cost||0))+'</b><button class="btn" onclick="editProductionCost(\''+x.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'production_costs\',\''+x.id+'\')">Delete</button></div></div>').join(''):empty('No production costs'))+'</div>'}
  function projectMoney(p,pay){return '<div class="section-bar"><div><h2>Money</h2><p>Project cash movement.</p></div><button class="btn primary" onclick="projectPayment(\''+p.id+'\')">Record payment</button></div>'+table(['Date','Direction','Amount','Method',''],pay.map(x=>'<tr><td>'+esc(x.payment_date||'—')+'</td><td>'+badge(x.direction)+'</td><td>'+money(x.amount)+'</td><td>'+esc(x.method||'—')+'</td><td><button class="btn" onclick="editPayment(\''+x.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'payments\',\''+x.id+'\')">Delete</button></td></tr>'))}
  function deliveryView(p,ds){return '<div class="section-bar"><div><h2>Aavartan delivery</h2><p>Edits, albums, drives and handover.</p></div><button class="btn primary" onclick="newDeliverable(\''+p.id+'\')">Add deliverable</button></div>'+table(['Deliverable','Due','Status',''],ds.map(d=>'<tr><td><b>'+esc(d.deliverable)+'</b></td><td>'+esc(d.due_date||'—')+'</td><td>'+badge(d.status)+'</td><td><button class="btn" onclick="editDeliverable(\''+d.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'aavartan_deliverables\',\''+d.id+'\')">Delete</button></td></tr>'))}
  function newInquiry(){modal('New inquiry','<div class="form-note">Required: customer name, event name and date.</div>'+field('Customer name','i_name')+field('Phone / WhatsApp','i_phone','tel')+field('Email','i_email','email')+field('Event / wedding name','i_event')+dateField('Event date','i_date')+field('Venue','i_venue')+field('Guest count','i_guests','number','','min="1"')+select('Lead source','i_source',['Instagram','Facebook','WhatsApp','Referral','Website','Other'])+field('Budget (optional)','i_budget','number','','min="0"')+area('Needs / notes','i_notes'),'<button class="btn primary" onclick="saveInquiry()">Save inquiry</button>');primeDate('i_date')}
  async function saveInquiry(){try{const name=$('#i_name').value.trim(),phone=$('#i_phone').value.trim(),customer= A.state.customers.find(c=>phone&&c.phone===phone)||await A.addRow('customers',{name,phone,whatsapp:phone,email:$('#i_email').value.trim()||null,notes:null});await A.addRow('inquiries',{customer_id:customer.id,source:$('#i_source').value,status:'new',owner_id:A.state.user.id,event_name:$('#i_event').value.trim(),event_date_bs:$('#i_dateBS').value,venue:$('#i_venue').value.trim()||null,guest_count:+$('#i_guests').value||null,budget:+$('#i_budget').value||null,notes:$('#i_notes').value.trim()||null});close();render();toast('Inquiry saved')}catch(e){toast(e.message||'Could not save inquiry',true)}}
  function editInquiry(id){const i=A.state.inquiries.find(x=>x.id===id),c=A.state.customers.find(x=>x.id===i.customer_id);modal('Edit inquiry',field('Customer name','ei_name','text',c?.name)+field('Phone / WhatsApp','ei_phone','tel',c?.phone)+field('Email','ei_email','email',c?.email)+field('Event / wedding name','ei_event','text',i.event_name)+dateField('Event date','ei_date',i.event_date_bs)+field('Venue','ei_venue','text',i.venue)+field('Guest count','ei_guests','number',i.guest_count||'', 'min="1"')+select('Stage','ei_status',Object.entries(STATUS).filter(([k])=>['new','contacted','qualified','quote_sent','negotiation','awaiting_advance','lost'].includes(k)).map(([k,v])=>[k,v]),i.status)+area('Notes','ei_notes',i.notes),'<button class="btn primary" onclick="saveInquiryEdit(\''+id+'\')">Save</button>');primeDate('ei_date')}
  async function saveInquiryEdit(id){try{const i=A.state.inquiries.find(x=>x.id===id),c=A.state.customers.find(x=>x.id===i.customer_id);await A.patch('customers',c.id,{name:$('#ei_name').value.trim(),phone:$('#ei_phone').value.trim(),whatsapp:$('#ei_phone').value.trim(),email:$('#ei_email').value.trim()||null});await A.patch('inquiries',id,{event_name:$('#ei_event').value.trim(),event_date_bs:$('#ei_dateBS').value,venue:$('#ei_venue').value.trim()||null,guest_count:+$('#ei_guests').value||null,status:$('#ei_status').value,notes:$('#ei_notes').value.trim()||null});close();render();toast('Inquiry updated')}catch(e){toast(e.message||'Could not update inquiry',true)}}
  async function convertInquiry(id){try{const i=A.state.inquiries.find(x=>x.id===id);if(A.state.projects.some(p=>p.inquiry_id===id)){toast('Project already exists');return}const p=await A.addRow('projects',{customer_id:i.customer_id,inquiry_id:i.id,name:i.event_name||'Event project',status:'planning',brand:'Rachna + Aavartan',date_range_bs:i.event_date_bs||null});const a=bs2ad(i.event_date_bs);await A.addRow('event_functions',{project_id:p.id,name:i.event_name||'Event',event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:i.event_date_bs||null,venue:i.venue||null,guest_count:i.guest_count||null});await A.patch('inquiries',id,{status:'awaiting_advance'});close();openP(p.id);toast('Project created from inquiry')}catch(e){toast(e.message||'Could not convert inquiry',true)}} window.convertInquiry=convertInquiry;
  function newProject(){const cs=A.state.customers.map(c=>[c.id,c.name+(c.phone?' · '+c.phone:'')]);modal('New project','<div class="form-note">Only project fields go here. Venue, guests and dates belong to the first function, so saving stays clean.</div>'+select('Customer','p_customer',[['','Select customer…'],...cs])+field('Project / wedding name','p_name')+select('Brand','p_brand',[['Rachna + Aavartan','Rachna + Aavartan'],['Aavartan','Aavartan'],['Rachna','Rachna']],'Rachna + Aavartan')+field('First function name','p_fn','text','Wedding')+dateField('First function date','p_date')+field('Venue','p_venue')+field('Guest count','p_guests','number','','min="1"'),'<button class="btn primary" onclick="saveProject()">Create project</button>');primeDate('p_date')}
  async function saveProject(){try{const p=await A.addRow('projects',{customer_id:$('#p_customer').value||null,name:$('#p_name').value.trim(),status:'planning',brand:$('#p_brand').value,date_range_bs:$('#p_dateBS').value});const a=bs2ad($('#p_dateBS').value);await A.addRow('event_functions',{project_id:p.id,name:$('#p_fn').value.trim()||'Wedding',event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#p_dateBS').value,venue:$('#p_venue').value.trim()||null,guest_count:+$('#p_guests').value||null});close();openP(p.id);toast('Project created')}catch(e){toast(e.message||'Could not save project',true)}}
  function editProject(id){const p=A.state.projects.find(x=>x.id===id);modal('Edit project',field('Project name','ep_name','text',p.name)+select('Brand','ep_brand',[['Rachna + Aavartan','Rachna + Aavartan'],['Aavartan','Aavartan'],['Rachna','Rachna']],p.brand)+select('Status','ep_status',[['planning','Planning'],['in_progress','In progress'],['completed','Completed'],['booked','Booked']],p.status),'<button class="btn primary" onclick="saveProjectEdit(\''+id+'\')">Save</button>')}
  async function saveProjectEdit(id){try{await A.patch('projects',id,{name:$('#ep_name').value.trim(),brand:$('#ep_brand').value,status:$('#ep_status').value});close();render();toast('Project updated')}catch(e){toast(e.message,true)}}
  async function deleteProject(id){if(!confirm('Delete this project and its attached functions, services, quotes, vendors, team, tasks, money and delivery records?'))return;try{for(const t of ['quotation_items','quotations','project_team','vendor_bookings','project_services','production_costs','aavartan_deliverables','tasks','payments','project_expenses','documents','event_functions']){const key=t==='quotation_items'?'quotation_id':null;const ids=A.state[t].filter(x=>key?A.state.quotations.some(q=>q.project_id===id&&q.id===x[key]):x.project_id===id).map(x=>x.id);for(const rid of ids)await A.remove(t,rid)}await A.remove('projects',id);go('projects');toast('Project deleted')}catch(e){toast(e.message||'Delete failed. Check linked records.',true)}} window.deleteProject=deleteProject;
  function newFunction(id){modal('Add function',field('Function name','f_name')+dateField('Function date','f_date',A.state.projects.find(p=>p.id===id)?.date_range_bs||'')+field('Venue','f_venue')+field('Guest count','f_guest','number','','min="1"')+field('Start time','f_time','time')+area('Notes','f_notes'),'<button class="btn primary" onclick="saveFunction(\''+id+'\')">Add function</button>');primeDate('f_date')}
  async function saveFunction(pid){try{const a=bs2ad($('#f_dateBS').value);await A.addRow('event_functions',{project_id:pid,name:$('#f_name').value.trim(),event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#f_dateBS').value,venue:$('#f_venue').value.trim()||null,guest_count:+$('#f_guest').value||null,start_time:$('#f_time').value||null,notes:$('#f_notes').value.trim()||null},false);close();render();toast('Function saved')}catch(e){toast(e.message,true)}}
  function editFunction(id){const f=A.state.functions.find(x=>x.id===id);modal('Edit function',field('Function name','efn','text',f.name)+dateField('Function date','efd',f.event_date_bs)+field('Venue','efv','text',f.venue||'')+field('Guest count','efg','number',f.guest_count||'','min="1"')+field('Start time','eft','time',f.start_time||'')+area('Notes','efnote',f.notes||''),'<button class="btn primary" onclick="saveFunctionEdit(\''+id+'\')">Save</button>');primeDate('efd')}
  async function saveFunctionEdit(id){try{const a=bs2ad($('#efdBS').value);await A.patch('event_functions',id,{name:$('#efn').value.trim(),event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#efdBS').value,venue:$('#efv').value.trim()||null,guest_count:+$('#efg').value||null,start_time:$('#eft').value||null,notes:$('#efnote').value.trim()||null});close();render();toast('Function updated')}catch(e){toast(e.message,true)}}
  function servicePicker(pid){const sel=A.state.projectServices.filter(x=>x.project_id===pid);const names=sel.map(x=>x.name);let html='<div class="service-group"><div class="group-title">Aavartan · core service</div><label class="check-card core"><input id="score" type="checkbox" '+(names.includes(CORE.name)?'checked':'')+'><span><strong>Photography + Videography</strong><small>One core service · starting '+money(CORE.price)+'</small></span></label></div><div class="service-group"><div class="group-title">Aavartan · optional add-ons</div><div class="check-grid">'+ADDONS.map(x=>'<label class="check-card compact"><input class="addon" type="checkbox" value="'+esc(x[0])+'" '+(names.includes(x[0])?'checked':'')+'><span><strong>'+esc(x[0])+'</strong><small>'+money(x[1])+'</small></span></label>').join('')+'</div></div><div class="service-group"><div class="group-title">Rachna · event management</div><div class="check-grid">'+RACHNA.map(x=>'<label class="check-card compact"><input class="rachna-opt" type="checkbox" value="'+esc(x)+'" '+(names.includes(x)?'checked':'')+'><span><strong>'+esc(x)+'</strong><small>Price set per quote</small></span></label>').join('')+'</div></div><div class="form-note">Tick what the customer selected. Photo + Video stays together.</div>';modal('Choose services',html,'<button class="btn primary" onclick="saveServiceSelection(\''+pid+'\')">Save selection</button>')}
  async function saveServiceSelection(pid){try{const existing=A.state.projectServices.filter(x=>x.project_id===pid);for(const x of existing)await A.remove('project_services',x.id);const jobs=[];if($('#score')?.checked)jobs.push(A.addRow('project_services',{project_id:pid,name:CORE.name,customer_price:CORE.price,internal_cost:0,quantity:1},false));document.querySelectorAll('.addon:checked').forEach(e=>{const a=ADDONS.find(x=>x[0]===e.value);jobs.push(A.addRow('project_services',{project_id:pid,name:a[0],customer_price:a[1],internal_cost:0,quantity:1},false))});document.querySelectorAll('.rachna-opt:checked').forEach(e=>jobs.push(A.addRow('project_services',{project_id:pid,name:e.value,customer_price:0,internal_cost:0,quantity:1},false)));await Promise.all(jobs);await A.recalc(pid);close();render();toast('Services saved')}catch(e){toast(e.message||'Services could not be saved',true)}}
  function editProjectService(id){const x=A.state.projectServices.find(s=>s.id===id);modal('Edit service line',field('Name','psn','text',x.name)+field('Customer price','psp','number',x.customer_price,'min="0"')+field('Internal cost','psi','number',x.internal_cost,'min="0"')+field('Quantity','psq','number',x.quantity||1,'min="1"'),'<button class="btn primary" onclick="saveProjectService(\''+id+'\')">Save</button>')}
  async function saveProjectService(id){try{const x=A.state.projectServices.find(s=>s.id===id);await A.patch('project_services',id,{name:$('#psn').value.trim(),customer_price:+$('#psp').value||0,internal_cost:+$('#psi').value||0,quantity:+$('#psq').value||1});await A.recalc(x.project_id);close();render();toast('Service updated')}catch(e){toast(e.message,true)}}
  async function delProjectService(id,pid){try{await A.remove('project_services',id);await A.recalc(pid);render();toast('Service deleted')}catch(e){toast(e.message,true)}}
  function newQuote(pid){A.sb.from('quotations').select('version').eq('project_id',pid).order('version',{ascending:false}).limit(1).maybeSingle().then(r=>{const v=(r.data?.version||0)+1;A.addRow('quotations',{project_id:pid,version:v,status:'draft',customer_total:0,internal_total:0,notes:null},false).then(()=>{A.recalc(pid);render();toast('Quotation created')}).catch(e=>toast(e.message,true))})}
  function openQuote(id){const q=A.state.quotations.find(x=>x.id===id),items=A.state.quotationItems.filter(x=>x.quotation_id===id);modal('Quotation version '+q.version,'<div class="grid two-col"><div class="card inner"><b>Customer total</b><div class="big-number">'+money(q.customer_total)+'</div></div><div class="card inner"><b>Status</b><div class="big-number">'+esc(STATUS[q.status]||q.status)+'</div></div></div>'+table(['Description','Qty','Price',''],items.map(i=>'<tr><td>'+esc(i.description)+'</td><td>'+esc(i.quantity)+'</td><td>'+money(i.customer_price)+'</td><td><button class="btn" onclick="editQuoteItem(\''+i.id+'\',\''+q.project_id+'\')">Edit</button><button class="btn danger" onclick="delQuoteItem(\''+i.id+'\',\''+q.project_id+'\')">Delete</button></td></tr>')),'<button class="btn primary" onclick="addQuoteItem(\''+id+'\',\''+q.project_id+'\')">Add line</button>')}
  function addQuoteItem(qid,pid){modal('Add quote line',field('Description','qi_d')+field('Quantity','qi_q','number','1','min="1"')+field('Customer price','qi_p','number','','min="0"')+field('Internal cost','qi_i','number','','min="0"'),'<button class="btn primary" onclick="saveQuoteItem(\''+qid+'\',\''+pid+'\')">Save</button>')}
  async function saveQuoteItem(qid,pid){try{await A.addRow('quotation_items',{quotation_id:qid,description:$('#qi_d').value.trim(),quantity:+$('#qi_q').value||1,customer_price:+$('#qi_p').value||0,internal_cost:+$('#qi_i').value||0},false);await A.recalc(pid);close();render();toast('Quote line saved')}catch(e){toast(e.message,true)}}
  function editQuoteItem(id,pid){const x=A.state.quotationItems.find(i=>i.id===id);modal('Edit quote line',field('Description','eqd','text',x.description)+field('Quantity','eqq','number',x.quantity||1,'min="1"')+field('Customer price','eqp','number',x.customer_price,'min="0"')+field('Internal cost','eqi','number',x.internal_cost,'min="0"'),'<button class="btn primary" onclick="saveQuoteItemEdit(\''+id+'\',\''+pid+'\')">Save</button>')}
  async function saveQuoteItemEdit(id,pid){try{await A.patch('quotation_items',id,{description:$('#eqd').value.trim(),quantity:+$('#eqq').value||1,customer_price:+$('#eqp').value||0,internal_cost:+$('#eqi').value||0});await A.recalc(pid);close();render();toast('Quote line updated')}catch(e){toast(e.message,true)}}
  async function delQuoteItem(id,pid){try{await A.remove('quotation_items',id);await A.recalc(pid);render();toast('Quote line deleted')}catch(e){toast(e.message,true)}}
  function openAdvance(id){const p=A.state.projects.find(x=>x.id===id),need=Number(p.quoted_total||0)*.3;modal('Record customer advance',field('Amount received now','av_amt','number','','min="1"')+'<div class="advance-rule"><b>30% booking rule</b><div>Required: '+money(need)+'</div><div>Received so far: '+money(p.customer_advance)+'</div></div>'+field('Payment method','av_method')+field('Reference','av_ref'),'<button class="btn primary" onclick="saveAdvanceFix(\''+id+'\')">Save advance</button>')}
  async function saveAdvanceFix(id){try{const n=+$('#av_amt').value;if(!(n>0))throw Error('Enter a valid advance');const r=await A.recordAdvance(id,n,$('#av_method').value,$('#av_ref').value);close();render();toast(r.booked?'Booking confirmed':'Advance recorded')}catch(e){toast(e.message||'Advance could not be saved',true)}}
  function vendorBooking(pid){modal('Vendor booking',select('Vendor','vbv',[['','Select vendor…'],...A.state.vendors.map(v=>[v.id,v.name])])+select('Function','vbf',[['','General / project'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+field('Quoted internal cost','vbc','number','','min="0"')+field('Vendor advance paid','vba','number','0','min="0"')+field('Final paid','vbfp','number','0','min="0"'),'<button class="btn primary" onclick="saveVendorBookingFix(\''+pid+'\')">Save</button>')}
  async function saveVendorBookingFix(pid){try{await A.addRow('vendor_bookings',{project_id:pid,vendor_id:$('#vbv').value,function_id:$('#vbf').value||null,quoted_cost:+$('#vbc').value||0,advance_paid:+$('#vba').value||0,final_paid:+$('#vbfp').value||0,status:'confirmed'},false);await A.recalc(pid);close();render();toast('Vendor booking saved')}catch(e){toast(e.message,true)}}
  function editVendorBooking(id){const v=A.state.vendorBookings.find(x=>x.id===id);modal('Edit vendor booking',field('Quoted cost','evbc','number',v.quoted_cost)+field('Advance paid','evba','number',v.advance_paid)+field('Final paid','evbf','number',v.final_paid)+select('Status','evbs',[['confirmed','Confirmed'],['pending','Pending'],['paid','Paid']],v.status),'<button class="btn primary" onclick="saveVendorBookingEdit(\''+id+'\')">Save</button>')}
  async function saveVendorBookingEdit(id){try{const v=A.state.vendorBookings.find(x=>x.id===id);await A.patch('vendor_bookings',id,{quoted_cost:+$('#evbc').value||0,advance_paid:+$('#evba').value||0,final_paid:+$('#evbf').value||0,status:$('#evbs').value});await A.recalc(v.project_id);close();render();toast('Vendor booking updated')}catch(e){toast(e.message,true)}}
  function teamAssign(pid){modal('Assign team member',select('Team member','tm',[['','Select…'],...A.state.team.filter(x=>x.active!==false).map(x=>[x.id,x.name+' · '+(x.role||'')])])+select('Function','tmf',[['','General'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+field('Rate / cost','tmr','number','','min="0"')+area('Responsibility','tmresp'),'<button class="btn primary" onclick="saveTeamFix(\''+pid+'\')">Assign</button>')}
  async function saveTeamFix(pid){try{await A.addRow('project_team',{project_id:pid,team_member_id:$('#tm').value,function_id:$('#tmf').value||null,rate:+$('#tmr').value||0,responsibility:$('#tmresp').value.trim()||null},false);await A.recalc(pid);close();render();toast('Team assigned')}catch(e){toast(e.message,true)}}
  function newProductionCost(pid){modal('Add production cost',select('Function','pcf',[['','General'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+field('Category','pcc','text','Photography / Video')+field('Description','pcd')+field('Quantity','pcq','number','1','min="1"')+field('Unit cost','pcu','number','','min="0"'),'<button class="btn primary" onclick="saveProductionCost(\''+pid+'\')">Save</button>')}
  async function saveProductionCost(pid){try{await A.addRow('production_costs',{project_id:pid,function_id:$('#pcf').value||null,brand:'Aavartan',category:$('#pcc').value,description:$('#pcd').value.trim(),quantity:+$('#pcq').value||1,unit_cost:+$('#pcu').value||0},false);await A.recalc(pid);close();render();toast('Cost saved')}catch(e){toast(e.message,true)}}
  function editProductionCost(id){const x=A.state.productionCosts.find(c=>c.id===id);modal('Edit production cost',field('Description','epcd','text',x.description)+field('Category','epcc','text',x.category||'Other')+field('Quantity','epcq','number',x.quantity||1)+field('Unit cost','epcu','number',x.unit_cost||0),'<button class="btn primary" onclick="saveProductionCostEdit(\''+id+'\')">Save</button>')}
  async function saveProductionCostEdit(id){try{const x=A.state.productionCosts.find(c=>c.id===id);await A.patch('production_costs',id,{description:$('#epcd').value.trim(),category:$('#epcc').value,quantity:+$('#epcq').value||1,unit_cost:+$('#epcu').value||0});await A.recalc(x.project_id);close();render();toast('Cost updated')}catch(e){toast(e.message,true)}}
  function projectPayment(pid){modal('Project payment',select('Direction','ppd',[['in','Customer received'],['out','Paid out']],'in')+field('Amount','ppa','number','','min="1"')+field('Payment date','ppdate','date',new Date().toISOString().slice(0,10))+field('Method','ppm')+field('Reference','ppr')+area('Notes','ppn'),'<button class="btn primary" onclick="saveProjectPayment(\''+pid+'\')">Save</button>')}
  async function saveProjectPayment(pid){try{await A.addRow('payments',{project_id:pid,direction:$('#ppd').value,party_type:'other',amount:+$('#ppa').value,payment_date:$('#ppdate').value||new Date().toISOString().slice(0,10),method:$('#ppm').value||null,reference:$('#ppr').value||null,notes:$('#ppn').value||null});close();render();toast('Payment saved')}catch(e){toast(e.message,true)}}
  function editPayment(id){const x=A.state.payments.find(p=>p.id===id);modal('Edit payment',select('Direction','epd',[['in','Customer received'],['out','Paid out']],x.direction)+field('Amount','epa','number',x.amount)+field('Payment date','epdt','date',x.payment_date)+field('Method','epm','text',x.method||'')+field('Reference','epr','text',x.reference||'')+area('Notes','epn',x.notes||''),'<button class="btn primary" onclick="savePaymentEdit(\''+id+'\')">Save</button>')}
  async function savePaymentEdit(id){try{await A.patch('payments',id,{direction:$('#epd').value,amount:+$('#epa').value,payment_date:$('#epdt').value,method:$('#epm').value||null,reference:$('#epr').value||null,notes:$('#epn').value||null});close();render();toast('Payment updated')}catch(e){toast(e.message,true)}}
  function globalPayment(){if(A.state.projects[0])projectPayment(A.state.projects[0].id);else toast('Create a project first',true)}
  function newDeliverable(pid){modal('Add deliverable',field('Deliverable','dn')+field('Due date','dd','date')+select('Status','ds',[['pending','Pending'],['in_progress','In progress'],['delivered','Delivered']],'pending'),'<button class="btn primary" onclick="saveDeliverableFix(\''+pid+'\')">Save</button>')}
  async function saveDeliverableFix(pid){try{await A.addRow('aavartan_deliverables',{project_id:pid,deliverable:$('#dn').value.trim(),due_date:$('#dd').value||null,status:$('#ds').value},false);close();render();toast('Deliverable saved')}catch(e){toast(e.message,true)}}
  function editDeliverable(id){const x=A.state.deliverables.find(d=>d.id===id);modal('Edit deliverable',field('Deliverable','edn','text',x.deliverable)+field('Due date','edd','date',x.due_date||'')+select('Status','eds',[['pending','Pending'],['in_progress','In progress'],['delivered','Delivered']],x.status),'<button class="btn primary" onclick="saveDeliverableEdit(\''+id+'\')">Save</button>')}
  async function saveDeliverableEdit(id){try{await A.patch('aavartan_deliverables',id,{deliverable:$('#edn').value.trim(),due_date:$('#edd').value||null,status:$('#eds').value});close();render();toast('Deliverable updated')}catch(e){toast(e.message,true)}}
  async function delRow(t,id){if(!confirm('Delete this record?'))return;try{await A.remove(t,id);render();toast('Deleted')}catch(e){toast(e.message||'Delete failed',true)}} window.delRow=delRow;
  function quickFunction(){const p=A.state.projects[0];if(p)newFunction(p.id);else newProject()}
  function customersManager(){modal('Customers',table(['Customer','Phone','Email',''],A.state.customers.map(c=>'<tr><td><b>'+esc(c.name)+'</b></td><td>'+esc(c.phone||'')+'</td><td>'+esc(c.email||'')+'</td><td><button class="btn" onclick="editCustomer(\''+c.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'customers\',\''+c.id+'\')">Delete</button></td></tr>')),'<button class="btn primary" onclick="newCustomer()">New customer</button>')}
  function newCustomer(){modal('New customer',field('Name','cn')+field('Phone','cp','tel')+field('WhatsApp','cw','tel')+field('Email','ce','email')+area('Notes','cno'),'<button class="btn primary" onclick="saveCustomer()">Save</button>')}
  async function saveCustomer(){try{await A.addRow('customers',{name:$('#cn').value.trim(),phone:$('#cp').value.trim()||null,whatsapp:$('#cw').value.trim()||$('#cp').value.trim()||null,email:$('#ce').value.trim()||null,notes:$('#cno').value.trim()||null});customersManager();toast('Customer saved')}catch(e){toast(e.message,true)}}
  function editCustomer(id){const c=A.state.customers.find(x=>x.id===id);modal('Edit customer',field('Name','ecn','text',c.name)+field('Phone','ecp','tel',c.phone||'')+field('WhatsApp','ecw','tel',c.whatsapp||'')+field('Email','ece','email',c.email||'')+area('Notes','ecno',c.notes||''),'<button class="btn primary" onclick="saveCustomerEdit(\''+id+'\')">Save</button>')}
  async function saveCustomerEdit(id){try{await A.patch('customers',id,{name:$('#ecn').value.trim(),phone:$('#ecp').value.trim()||null,whatsapp:$('#ecw').value.trim()||null,email:$('#ece').value.trim()||null,notes:$('#ecno').value.trim()||null});close();render();toast('Customer updated')}catch(e){toast(e.message,true)}}
  function vendorsManager(){modal('Vendors',table(['Vendor','Category','Area','Phone',''],A.state.vendors.map(v=>'<tr><td><b>'+esc(v.name)+'</b></td><td>'+esc(v.service_category||'')+'</td><td>'+esc(v.area||'')+'</td><td>'+esc(v.phone||'')+'</td><td><button class="btn" onclick="editVendor(\''+v.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'vendors\',\''+v.id+'\')">Delete</button></td></tr>')),'<button class="btn primary" onclick="newVendor()">New vendor</button>')}
  function newVendor(){modal('New vendor',field('Name','vn')+field('Phone','vp','tel')+field('Category','vc')+field('Area','va')+field('Rate guide','vr')+select('Reliability','vrel',['Low','Medium','High'],'Medium')+area('Notes','vno'),'<button class="btn primary" onclick="saveVendor()">Save</button>')}
  async function saveVendor(){try{await A.addRow('vendors',{name:$('#vn').value.trim(),phone:$('#vp').value.trim()||null,service_category:$('#vc').value.trim()||null,area:$('#va').value.trim()||null,rate_guide:$('#vr').value.trim()||null,reliability:$('#vrel').value,notes:$('#vno').value.trim()||null});vendorsManager();toast('Vendor saved')}catch(e){toast(e.message,true)}}
  function editVendor(id){const v=A.state.vendors.find(x=>x.id===id);modal('Edit vendor',field('Name','evn','text',v.name)+field('Phone','evp','tel',v.phone||'')+field('Category','evc','text',v.service_category||'')+field('Area','eva','text',v.area||'')+field('Rate guide','evr','text',v.rate_guide||'')+select('Reliability','evrel',['Low','Medium','High'],v.reliability||'Medium')+area('Notes','evno',v.notes||''),'<button class="btn primary" onclick="saveVendorEdit(\''+id+'\')">Save</button>')}
  async function saveVendorEdit(id){try{await A.patch('vendors',id,{name:$('#evn').value.trim(),phone:$('#evp').value.trim()||null,service_category:$('#evc').value.trim()||null,area:$('#eva').value.trim()||null,rate_guide:$('#evr').value.trim()||null,reliability:$('#evrel').value,notes:$('#evno').value.trim()||null});close();render();toast('Vendor updated')}catch(e){toast(e.message,true)}}
  function teamManager(){modal('Team',table(['Name','Role','Phone','Active',''],A.state.team.map(t=>'<tr><td><b>'+esc(t.name)+'</b></td><td>'+esc(t.role||'')+'</td><td>'+esc(t.phone||'')+'</td><td>'+esc(t.active===false?'No':'Yes')+'</td><td><button class="btn" onclick="editTeam(\''+t.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'team_members\',\''+t.id+'\')">Delete</button></td></tr>')),'<button class="btn primary" onclick="newTeam()">New member</button>')}
  function newTeam(){modal('New team member',field('Name','tn')+field('Role','tr')+field('Phone','tp','tel')+field('Email','te','email')+select('Active','ta',[['true','Yes'],['false','No']],'true'),'<button class="btn primary" onclick="saveTeam()">Save</button>')}
  async function saveTeam(){try{await A.addRow('team_members',{name:$('#tn').value.trim(),role:$('#tr').value.trim()||null,phone:$('#tp').value.trim()||null,email:$('#te').value.trim()||null,active:$('#ta').value==='true'});teamManager();toast('Team member saved')}catch(e){toast(e.message,true)}}
  function editTeam(id){const t=A.state.team.find(x=>x.id===id);modal('Edit team member',field('Name','etn','text',t.name)+field('Role','etr','text',t.role||'')+field('Phone','etp','tel',t.phone||'')+field('Email','ete','email',t.email||'')+select('Active','eta',[['true','Yes'],['false','No']],t.active===false?'false':'true'),'<button class="btn primary" onclick="saveTeamEdit(\''+id+'\')">Save</button>')}
  async function saveTeamEdit(id){try{await A.patch('team_members',id,{name:$('#etn').value.trim(),role:$('#etr').value.trim()||null,phone:$('#etp').value.trim()||null,email:$('#ete').value.trim()||null,active:$('#eta').value==='true'});close();render();toast('Team updated')}catch(e){toast(e.message,true)}}
  function servicesManager(){modal('Service catalog',table(['Brand','Service','Category','Customer price','Internal cost',''],A.state.services.map(s=>'<tr><td>'+esc(s.brand)+'</td><td><b>'+esc(s.name)+'</b></td><td>'+esc(s.category||'')+'</td><td>'+money(s.base_price)+'</td><td>'+money(s.internal_cost)+'</td><td><button class="btn" onclick="editCatalogService(\''+s.id+'\')">Edit</button><button class="btn danger" onclick="delRow(\'services\',\''+s.id+'\')">Delete</button></td></tr>')),'<button class="btn primary" onclick="newCatalogService()">New service</button>')}
  function newCatalogService(){modal('New service',select('Brand','snbrand',['Rachna','Aavartan'])+field('Name','sn')+field('Category','sc')+field('Base price','sp','number','0')+field('Internal cost','si','number','0')+select('Active','sa',[['true','Yes'],['false','No']],'true'),'<button class="btn primary" onclick="saveCatalogService()">Save</button>')}
  async function saveCatalogService(){try{await A.addRow('services',{brand:$('#snbrand').value,name:$('#sn').value.trim(),category:$('#sc').value.trim()||null,base_price:+$('#sp').value||0,internal_cost:+$('#si').value||0,active:$('#sa').value==='true'});servicesManager();toast('Service saved')}catch(e){toast(e.message,true)}}
  function editCatalogService(id){const s=A.state.services.find(x=>x.id===id);modal('Edit service',select('Brand','esb',['Rachna','Aavartan'],s.brand)+field('Name','esn','text',s.name)+field('Category','escat','text',s.category||'')+field('Base price','esp','number',s.base_price)+field('Internal cost','esi','number',s.internal_cost)+select('Active','esa',[['true','Yes'],['false','No']],s.active===false?'false':'true'),'<button class="btn primary" onclick="saveCatalogServiceEdit(\''+id+'\')">Save</button>')}
  async function saveCatalogServiceEdit(id){try{await A.patch('services',id,{brand:$('#esb').value,name:$('#esn').value.trim(),category:$('#escat').value.trim()||null,base_price:+$('#esp').value||0,internal_cost:+$('#esi').value||0,active:$('#esa').value==='true'});close();render();toast('Service updated')}catch(e){toast(e.message,true)}}
  function authFix(){A.state.user?modal('Account','<div class="detail-grid"><div><span>Name</span><b>'+esc(A.state.profile?.full_name||'Owner')+'</b></div><div><span>Email</span><b>'+esc(A.state.user.email||'')+'</b></div></div>','<button class="btn primary" onclick="A.signOut()">Sign out</button>'):modal('Sign in',field('Email','ae','email')+field('Password','ap','password'),'<button class="btn primary" onclick="fixSignIn()">Sign in</button>')}
  async function fixSignIn(){try{await A.signIn($('#ae').value,$('#ap').value);close();render();toast('Signed in')}catch(e){toast(e.message,true)}}
  window.authFix=authFix;
  function initNav(){if($('#nav'))$('#nav').innerHTML=nav.map(n=>'<button class="nav-item" data-page="'+n[0]+'" onclick="go(\''+n[0+'\')"><span class="nav-dot"></span>'+n[1]+'</button>').join('')}
  if($('#nav')){$('#nav').innerHTML=nav.map(n=>'<button class="nav-item" data-page="'+n[0]+'" onclick="go(\''+n[0]+'\')"><span class="nav-dot"></span>'+n[1]+'</button>').join('');$('#refresh').onclick=()=>A.refresh().then(()=>{render();toast('Data refreshed')}).catch(e=>toast(e.message,true));$('#authBtn').onclick=authFix;$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')close()}}
  Object.assign(window,{newInquiry,editInquiry,saveInquiry,newProject,saveProject,editProject,saveProjectEdit,newFunction,saveFunction,editFunction,saveFunctionEdit,servicePicker,saveServiceSelection,editProjectService,saveProjectService,delProjectService,newQuote,openQuote,addQuoteItem,saveQuoteItem,editQuoteItem,saveQuoteItemEdit,delQuoteItem,openAdvance,saveAdvanceFix,vendorBooking,saveVendorBookingFix,editVendorBooking,saveVendorBookingEdit,teamAssign,saveTeamFix,newProductionCost,saveProductionCost,editProductionCost,saveProductionCostEdit,projectPayment,saveProjectPayment,editPayment,savePaymentEdit,globalPayment,newDeliverable,saveDeliverableFix,editDeliverable,saveDeliverableEdit,quickFunction,customersManager,newCustomer,saveCustomer,editCustomer,saveCustomerEdit,vendorsManager,newVendor,saveVendor,editVendor,saveVendorEdit,teamManager,newTeam,saveTeam,editTeam,saveTeamEdit,servicesManager,newCatalogService,saveCatalogService,editCatalogService,saveCatalogServiceEdit,openP,deleteProject,convertInquiry});
  try{render()}catch(e){console.error(e);toast(e.message||'UI failed',true)}
})();