(()=>{
const A=window.RachnaAPI,$=s=>document.querySelector(s),esc=A.esc,money=A.money;
const MONTHS=['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'];
const CORE=['Aavartan Photo + Video',45000];
const ADDONS=[['Candid coverage',12000],['Cinematic coverage',15000],['Drone',8000],['Premium Karizma album',10000],['Social media reels',15000],['Additional photographer',12000],['Additional videographer',12000],['Pre-wedding',25000],['Post-wedding',25000],['Additional album',5000]];
const RACHNA=['Decoration / stage design','Venue coordination','Catering coordination','Makeup & beauty','Mehendi','Band / DJ / artists','Wedding car / transport','Panche baja','Event coordination'];
const ST={new:'New',contacted:'Contacted',qualified:'Qualified',quote_sent:'Quote sent',negotiation:'Negotiation',awaiting_advance:'Awaiting advance',booked:'Booked',lost:'Lost',planning:'Planning',in_progress:'In progress',completed:'Completed',pending:'Pending',delivered:'Delivered'};
const ORG=['customers','inquiries','projects','services','vendors','tasks','payments','project_expenses','team_members','documents','marketing_leads'];
let page='home',projectId=null,tab='overview',search='';
A.insertRow=async(t,row)=>{const x={...row};if(ORG.includes(t))x.organization_id=A.state.profile?.organization_id;const r=await A.sb.from(t).insert(x).select().single();if(r.error)throw r.error;await A.refresh();return r.data};
A.editRow=async(t,id,row)=>{const r=await A.sb.from(t).update(row).eq('id',id).select().maybeSingle();if(r.error)throw r.error;await A.refresh();return r.data};
A.deleteRow=async(t,id)=>{const r=await A.sb.from(t).delete().eq('id',id);if(r.error)throw r.error;await A.refresh()};
const toast=(m,e=false)=>{const t=$('#toast');t.textContent=m;t.className='toast show '+(e?'error':'');clearTimeout(window.__toast3);window.__toast3=setTimeout(()=>t.className='toast',3000)};
const close=()=>$('#backdrop').classList.remove('show');window.__close3=close;
const modal=(title,body,actions)=>{$('#modal').innerHTML=`<div class="modal-head"><div><div class="eyebrow">Rachna OS</div><h2>${title}</h2></div><button class="close-btn" onclick="window.__close3()">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="btn" onclick="window.__close3()">Cancel</button>${actions||''}</div>`;$('#backdrop').classList.add('show')};
const fld=(l,id,type='text',v='',x='')=>`<div class="field"><label>${esc(l)}</label><input id="${id}" type="${type}" value="${esc(v??'')}" ${x}></div>`;
const area=(l,id,v='')=>`<div class="field full"><label>${esc(l)}</label><textarea id="${id}">${esc(v??'')}</textarea></div>`;
const sel=(l,id,opts,v='')=>`<div class="field"><label>${esc(l)}</label><select id="${id}">${opts.map(o=>{const a=Array.isArray(o)?o:[o,o];return `<option value="${esc(a[0])}" ${String(a[0])===String(v)?'selected':''}>${esc(a[1])}</option>`}).join('')}</select></div>`;
function conv(){return window.DateConverter||null}function bs2ad(v){try{const X=conv();return X&&v?new X(v).toAd():null}catch{return null}}function ad2bs(v){try{const X=conv();return X&&v?new X(v).toBs():null}catch{return null}}
function validDays(y,m){const X=conv(),a=[];if(X){for(let d=1;d<=32;d++){try{new X(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`).toAd();a.push(d)}catch{}}}return a.length?a:Array.from({length:32},(_,i)=>i+1)}
function bsField(label,key,value=''){let p=ad2bs(new Date().toISOString().slice(0,10))||{year:2083,month:6,date:18};if(value&&bs2ad(value)){const z=value.split('-').map(Number);p={year:z[0],month:z[1],date:z[2]}}const ds=validDays(p.year,p.month),d=ds.includes(p.date)?p.date:ds[ds.length-1];return `<div class="field full"><label>${esc(label)} · BS</label><div class="date-grid"><select id="${key}Y" onchange="window.__date3('${key}')">${Array.from({length:25},(_,i)=>2075+i).map(y=>`<option value="${y}" ${y===p.year?'selected':''}>${y}</option>`).join('')}</select><select id="${key}M" onchange="window.__date3('${key}')">${MONTHS.map((m,i)=>`<option value="${i+1}" ${i+1===p.month?'selected':''}>${m}</option>`).join('')}</select><select id="${key}D" onchange="window.__date3('${key}')">${ds.map(x=>`<option value="${x}" ${x===d?'selected':''}>${x}</option>`).join('')}</select></div><input id="${key}BS" type="hidden" value="${esc(value||`${p.year}-${String(p.month).padStart(2,'0')}-${String(d).padStart(2,'0')}`)}"><div id="${key}AD" class="date-preview"></div></div>`}
window.__date3=k=>{const y=+$('#'+k+'Y').value,m=+$('#'+k+'M').value,ds=validDays(y,m),old=+$('#'+k+'D').value,d=ds.includes(old)?old:ds[ds.length-1];$('#'+k+'D').innerHTML=ds.map(x=>`<option value="${x}" ${x===d?'selected':''}>${x}</option>`).join('');const bs=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;$('#'+k+'BS').value=bs;const a=bs2ad(bs);$('#'+k+'AD').textContent=a?`AD ${String(a.date).padStart(2,'0')} ${MONTHS[a.month-1]} ${a.year}`:'Unable to convert'};
const badge=v=>{const c=/booked|completed|done|delivered|paid/i.test(v)?'green':/new|pending|planning|negotiation|awaiting|qualified|contacted|quote_sent|in_progress/i.test(v)?'amber':'gold';return `<span class="tag ${c}">${esc(ST[v]||v||'—')}</span>`};
const head=(e,t,s,a='')=>`<div class="page-head"><div><div class="eyebrow">${esc(e)}</div><h1>${t}</h1><p>${s}</p></div><div class="action-row">${a}</div></div>`;
const kpi=(l,v,f)=>`<div class="card kpi"><small>${esc(l)}</small><strong>${v}</strong><span>${esc(f)}</span></div>`;
const empty=(t,s='')=>`<div class="empty-state"><strong>${esc(t)}</strong><span>${esc(s)}</span></div>`;
const table=(h,rows)=>`<div class="card table-wrap"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${h.length}">${empty('No records')}</td></tr>`}</tbody></table></div>`;
const nav=[['home','Home'],['inquiries','Inquiries'],['projects','Projects'],['calendar','Calendar'],['money','Money'],['settings','Settings']];
function render(){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#crumb').textContent=projectId?'Project':(nav.find(x=>x[0]===page)||nav[0])[1];$('#page').innerHTML=projectId?project():({home,inquiries,projects,calendar,money:moneyPage,settings}[page]||home)}
function go(p){page=p;projectId=null;tab='overview';render()}window.go=go;function openProject(id){projectId=id;tab='overview';render()}window.openProject=openProject;
function home(){const s=A.state,next=s.functions.filter(f=>f.event_date).slice().sort((a,b)=>a.event_date.localeCompare(b.event_date)).slice(0,5);return head('Rachna + Aavartan','Event command centre','Inquiry → Project → Functions → Services → Quote → Advance → Booked.','<button class="btn" onclick="newInquiry3()">New inquiry</button><button class="btn primary" onclick="newProject3()">New project</button>')+`<div class="grid four-col">${kpi('Open inquiries',s.inquiries.filter(x=>!['booked','lost'].includes(x.status)).length,'Sales pipeline')}${kpi('Booked projects',s.projects.filter(x=>x.status==='booked').length,'30% advance')}${kpi('Cash received',money(s.payments.filter(x=>x.direction==='in').reduce((a,x)=>a+Number(x.amount||0),0)),'Incoming')}${kpi('Upcoming functions',next.length,'Scheduled')}</div><div class="card how"><div><div class="eyebrow">AAVARTAN PRIORITY</div><h2>Photography + Videography are ONE core service.</h2><p>All other Aavartan options are optional checkboxes. Rachna manages the event planning and management side.</p></div><div class="flow"><div>1<small>Inquiry</small></div><span>→</span><div>2<small>Project</small></div><span>→</span><div>3<small>Services</small></div><span>→</span><div>4<small>Quote</small></div><span>→</span><div>5<small>30%</small></div><span>→</span><div>6<small>Booked</small></div></div></div>`}
function inquiries(){const rows=A.state.inquiries.map(i=>{const c=A.state.customers.find(x=>x.id===i.customer_id);return `<tr><td><b>${esc(i.event_name||'Untitled')}</b><div class="muted">${esc(i.event_date_bs||'Date TBC')}</div></td><td>${esc(c?.name||'—')}<div class="muted">${esc(c?.phone||'')}</div></td><td>${esc(i.venue||'Venue TBC')}</td><td>${badge(i.status)}</td><td class="row-actions"><button class="btn tiny" onclick="editInquiry3('${i.id}')">Edit</button><button class="btn tiny" onclick="convertInquiry3('${i.id}')">Project</button><button class="btn tiny danger" onclick="del3('inquiries','${i.id}')">Delete</button></td></tr>`});return head('Sales','Inquiries','One place for every new lead.','<button class="btn primary" onclick="newInquiry3()">New inquiry</button>')+table(['Event','Customer','Venue','Stage',''],rows)}
function projects(){const rows=A.state.projects.filter(p=>!search||p.name.toLowerCase().includes(search.toLowerCase())).map(p=>{const c=A.state.customers.find(x=>x.id===p.customer_id);return `<tr><td><b>${esc(p.name)}</b><div class="muted">${esc(p.date_range_bs||'')}</div></td><td>${esc(c?.name||'—')}</td><td>${esc(p.brand||'')}</td><td>${money(p.quoted_total)}</td><td>${money(p.customer_advance)}</td><td>${badge(p.status)}</td><td class="row-actions"><button class="btn tiny" onclick="openProject('${p.id}')">Open</button><button class="btn tiny" onclick="editProject3('${p.id}')">Edit</button><button class="btn tiny danger" onclick="deleteProject3('${p.id}')">Delete</button></td></tr>`});return head('Production','Projects','One master project per wedding/event.','<input class="search" placeholder="Search" value="'+esc(search)+'" oninput="search=this.value;render()"><button class="btn primary" onclick="newProject3()">New project</button>')+table(['Project','Customer','Brand','Quoted','Advance','Status',''],rows)}
function calendar(){const fs=A.state.functions.filter(f=>f.event_date).slice().sort((a,b)=>a.event_date.localeCompare(b.event_date));return head('Planning','Calendar','BS date is primary; AD is automatic.','<button class="btn primary" onclick="quickFunction3()">Add function</button>')+'<div class="calendar-list">'+(fs.length?fs.map(f=>{const p=A.state.projects.find(x=>x.id===f.project_id);return `<div class="card calendar-card"><div class="calendar-date"><b>${esc(f.event_date_bs||'—')}</b><small>${esc(f.event_date||'')}</small></div><div><h3>${esc(f.name)}</h3><p>${esc(p?.name||'Project')} · ${esc(f.venue||'Venue TBC')}</p></div><div class="row-actions"><button class="btn tiny" onclick="editFunction3('${f.id}')">Edit</button><button class="btn tiny danger" onclick="del3('event_functions','${f.id}')">Delete</button></div></div>`}).join(''):empty('No dates yet'))+'</div>'}
function moneyPage(){const i=A.state.payments.filter(x=>x.direction==='in').reduce((a,x)=>a+Number(x.amount||0),0),o=A.state.payments.filter(x=>x.direction==='out').reduce((a,x)=>a+Number(x.amount||0),0);return head('Finance','Money','Actual receipts and outgoing payments.','<button class="btn primary" onclick="globalPayment3()">Record payment</button>')+`<div class="grid three-col">${kpi('Cash in',money(i),'Incoming')}${kpi('Cash out',money(o),'Outgoing')}${kpi('Net',money(i-o),'Recorded')}</div>`+table(['Date','Project','Direction','Amount','Method',''],A.state.payments.slice(0,50).map(p=>`<tr><td>${esc(p.payment_date||'')}</td><td>${esc(A.state.projects.find(x=>x.id===p.project_id)?.name||'—')}</td><td>${badge(p.direction)}</td><td>${money(p.amount)}</td><td>${esc(p.method||'')}</td><td class="row-actions"><button class="btn tiny" onclick="editPayment3('${p.id}')">Edit</button><button class="btn tiny danger" onclick="del3('payments','${p.id}')">Delete</button></td></tr>`))}
function settings(){return head('Workspace','Settings','Manage master data.','<button class="btn" onclick="account3()">Account</button>')+`<div class="manage-grid"><div class="manage-card"><h2>Business rules</h2><p><b>Rachna:</b> event planning + management.</p><p><b>Aavartan:</b> Photo + Video is one core service; the rest are add-ons.</p><p><b>Booking:</b> 30% customer advance confirms the project.</p></div><div class="manage-card"><h2>Master data</h2><div class="row-actions"><button class="btn" onclick="customerManager3()">Customers</button><button class="btn" onclick="vendorManager3()">Vendors</button><button class="btn" onclick="teamManager3()">Team</button><button class="btn" onclick="serviceManager3()">Services</button></div></div></div>`}
function project(){const p=A.state.projects.find(x=>x.id===projectId);if(!p){projectId=null;return projects()}const c=A.state.customers.find(x=>x.id===p.customer_id),fs=A.state.functions.filter(x=>x.project_id===p.id),ps=A.state.projectServices.filter(x=>x.project_id===p.id),vb=A.state.vendorBookings.filter(x=>x.project_id===p.id),pt=A.state.projectTeam.filter(x=>x.project_id===p.id),pc=A.state.productionCosts.filter(x=>x.project_id===p.id),pay=A.state.payments.filter(x=>x.project_id===p.id),ds=A.state.deliverables.filter(x=>x.project_id===p.id),qs=A.state.quotations.filter(x=>x.project_id===p.id);let body='';if(tab==='overview')body=`<div class="grid four-col">${kpi('Functions',fs.length,'Events')}${kpi('Services',ps.length,'Selected')}${kpi('Vendors',vb.length,'Bookings')}${kpi('Advance',money(p.customer_advance),'30% rule')}</div><div class="grid two-col"><div class="card"><h2>${esc(p.name)}</h2><div class="detail-list"><div><span>Customer</span><b>${esc(c?.name||'—')}</b></div><div><span>Phone</span><b>${esc(c?.phone||'—')}</b></div><div><span>Date range</span><b>${esc(p.date_range_bs||'—')}</b></div><div><span>Status</span>${badge(p.status)}</div></div></div><div class="card"><div class="eyebrow">AAVARTAN</div><h2>Photo + Video</h2><p>Core service. Optional extras are checkboxes.</p></div></div>`;
else if(tab==='functions')body=`<div class="section-bar"><div><h2>Functions</h2><p>Mehendi, Haldi, Engagement, Wedding, Reception, etc.</p></div><button class="btn primary" onclick="newFunction3('${p.id}')">Add function</button></div><div class="function-grid">${fs.length?fs.map(f=>`<div class="card function-card"><div class="eyebrow">FUNCTION</div><h3>${esc(f.name)}</h3><b>${esc(f.event_date_bs||'Date TBC')}</b><small>${esc(f.event_date||'')}</small><small>${esc(f.venue||'Venue TBC')} · ${esc(f.guest_count||0)} guests</small><div class="row-actions"><button class="btn tiny" onclick="editFunction3('${f.id}')">Edit</button><button class="btn tiny danger" onclick="del3('event_functions','${f.id}')">Delete</button></div></div>`).join(''):empty('No functions yet')}</div>`;
else if(tab==='services')body=`<div class="section-bar"><div><h2>Services</h2><p>Aavartan core + optional checkboxes; Rachna options below.</p></div><button class="btn primary" onclick="servicePicker3('${p.id}')">Choose services</button></div><div class="card feature-card"><div><div class="eyebrow">CORE</div><h2>Photography + Videography</h2><p>One combined Aavartan service.</p></div><b>${money(CORE[1])}</b></div>${table(['Service','Qty','Customer','Internal',''],ps.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.quantity||1)}</td><td>${money(x.customer_price)}</td><td>${money(x.internal_cost)}</td><td class="row-actions"><button class="btn tiny" onclick="editPS3('${x.id}')">Edit</button><button class="btn tiny danger" onclick="delPS3('${x.id}','${p.id}')">Delete</button></td></tr>`))}`;
else if(tab==='quote'){const q=[...qs].sort((a,b)=>Number(b.version)-Number(a.version))[0];body=`<div class="section-bar"><div><h2>Quote</h2><p>Create a new version when pricing changes.</p></div><button class="btn primary" onclick="newQuote3('${p.id}')">New quotation</button></div>`+(q?`<div class="card quote-card"><div><div class="eyebrow">VERSION ${q.version}</div><h2>${badge(q.status)}</h2><p>Total: <b>${money(q.customer_total)}</b></p></div><button class="btn" onclick="quote3('${q.id}')">Open</button></div>`:empty('No quotation yet'))}
else if(tab==='operations')body=`<div class="grid two-col"><div class="card"><div class="section-bar"><h2>Vendors</h2><button class="btn" onclick="newVendorBooking3('${p.id}')">Add</button></div>${vb.length?vb.map(v=>`<div class="list-row"><div><b>${esc(A.state.vendors.find(x=>x.id===v.vendor_id)?.name||'Vendor')}</b><div class="muted">${esc(A.state.functions.find(f=>f.id===v.function_id)?.name||'General')}</div></div><div class="row-actions"><b>${money(v.quoted_cost)}</b><button class="btn tiny" onclick="editVB3('${v.id}')">Edit</button><button class="btn tiny danger" onclick="del3('vendor_bookings','${v.id}')">Delete</button></div></div>`).join(''):empty('No vendors')}</div><div class="card"><div class="section-bar"><h2>Team</h2><button class="btn" onclick="assignTeam3('${p.id}')">Assign</button></div>${pt.length?pt.map(v=>`<div class="list-row"><div><b>${esc(A.state.team.find(t=>t.id===v.team_member_id)?.name||'Team')}</b></div><div class="row-actions"><b>${money(v.rate)}</b><button class="btn tiny danger" onclick="del3('project_team','${v.id}')">Delete</button></div></div>`).join(''):empty('No team')}</div></div><div class="card" style="margin-top:15px"><div class="section-bar"><h2>Production costs</h2><button class="btn" onclick="newCost3('${p.id}')">Add</button></div>${pc.length?pc.map(v=>`<div class="list-row"><div><b>${esc(v.description)}</b></div><div class="row-actions"><b>${money(Number(v.quantity||1)*Number(v.unit_cost||0))}</b><button class="btn tiny" onclick="editCost3('${v.id}')">Edit</button><button class="btn tiny danger" onclick="del3('production_costs','${v.id}')">Delete</button></div></div>`).join(''):empty('No costs')}</div>`;
else if(tab==='money')body=`<div class="section-bar"><div><h2>Money</h2></div><button class="btn primary" onclick="projectPayment3('${p.id}')">Record payment</button></div>${table(['Date','Direction','Amount','Method',''],pay.map(v=>`<tr><td>${esc(v.payment_date||'')}</td><td>${badge(v.direction)}</td><td>${money(v.amount)}</td><td>${esc(v.method||'')}</td><td class="row-actions"><button class="btn tiny" onclick="editPayment3('${v.id}')">Edit</button><button class="btn tiny danger" onclick="del3('payments','${v.id}')">Delete</button></td></tr>`))}`;
else body=`<div class="section-bar"><div><h2>Delivery</h2></div><button class="btn primary" onclick="newDelivery3('${p.id}')">Add</button></div>${table(['Deliverable','Due','Status',''],ds.map(v=>`<tr><td>${esc(v.deliverable)}</td><td>${esc(v.due_date||'')}</td><td>${badge(v.status)}</td><td class="row-actions"><button class="btn tiny" onclick="editDelivery3('${v.id}')">Edit</button><button class="btn tiny danger" onclick="del3('aavartan_deliverables','${v.id}')">Delete</button></td></tr>`))}`;
const tabs=[['overview','Overview'],['functions','Functions'],['services','Services'],['quote','Quote'],['operations','Vendors & Team'],['money','Money'],['delivery','Delivery']];return head('Project',esc(p.name),esc(c?.name||'Customer'),`<button class="btn" onclick="go('projects')">Back</button><button class="btn" onclick="editProject3('${p.id}')">Edit</button><button class="btn primary" onclick="advance3('${p.id}')">30% advance</button>`)+`<div class="project-summary"><div><span>Quoted</span><b>${money(p.quoted_total)}</b></div><div><span>Advance</span><b>${money(p.customer_advance)}</b></div><div><span>Due</span><b>${money(Math.max(0,Number(p.quoted_total)-Number(p.customer_advance)))}</b></div></div><div class="subnav">${tabs.map(x=>`<button class="subnav-btn ${tab===x[0]?'active':''}" onclick="tab='${x[0]}';render()">${x[1]}</button>`).join('')}</div>${body}`}
function newInquiry3(){modal('New inquiry',fld('Customer name','in')+fld('Phone / WhatsApp','ip','tel')+fld('Email','ie','email')+fld('Event / wedding name','iev')+bsField('Event date','idate')+fld('Venue','iv')+fld('Guest count','ig','number')+sel('Source','isrc',['Instagram','Facebook','WhatsApp','Referral','Website','Other'])+fld('Budget (optional)','ib','number')+area('Notes','inote'),'<button class="btn primary" onclick="saveInquiry3()">Save inquiry</button>');setTimeout(()=>window.__date3('idate'),0)}
async function saveInquiry3(){try{const name=$('#in').value.trim(),phone=$('#ip').value.trim();let c=A.state.customers.find(x=>phone&&x.phone===phone);if(!c)c=await A.insertRow('customers',{name,phone:phone||null,whatsapp:phone||null,email:$('#ie').value.trim()||null,notes:null});await A.insertRow('inquiries',{customer_id:c.id,source:$('#isrc').value,status:'new',owner_id:A.state.user.id,event_name:$('#iev').value.trim(),event_date_bs:$('#idateBS').value,venue:$('#iv').value.trim()||null,guest_count:+$('#ig').value||null,budget:+$('#ib').value||null,notes:$('#inote').value.trim()||null});close();render();toast('Inquiry saved')}catch(e){toast(e.message||'Inquiry save failed',true)}}
function editInquiry3(id){const i=A.state.inquiries.find(x=>x.id===id),c=A.state.customers.find(x=>x.id===i.customer_id);modal('Edit inquiry',fld('Customer name','ein','text',c?.name)+fld('Phone / WhatsApp','eip','tel',c?.phone||'')+fld('Email','eie','email',c?.email||'')+fld('Event name','eiev','text',i.event_name)+bsField('Event date','eid',i.event_date_bs)+fld('Venue','eiv','text',i.venue||'')+fld('Guest count','eig','number',i.guest_count||'')+sel('Stage','eis',Object.entries(ST).filter(x=>['new','contacted','qualified','quote_sent','negotiation','awaiting_advance','lost'].includes(x[0])).map(x=>[x[0],x[1]]),i.status)+area('Notes','einote',i.notes||''),`<button class="btn primary" onclick="saveInquiryEdit3('${id}')">Save</button>`);setTimeout(()=>window.__date3('eid'),0)}
async function saveInquiryEdit3(id){try{const i=A.state.inquiries.find(x=>x.id===id),c=A.state.customers.find(x=>x.id===i.customer_id);if(c)await A.editRow('customers',c.id,{name:$('#ein').value.trim(),phone:$('#eip').value.trim()||null,whatsapp:$('#eip').value.trim()||null,email:$('#eie').value.trim()||null});await A.editRow('inquiries',id,{event_name:$('#eiev').value.trim(),event_date_bs:$('#eidBS').value,venue:$('#eiv').value.trim()||null,guest_count:+$('#eig').value||null,status:$('#eis').value,notes:$('#einote').value.trim()||null});close();render();toast('Inquiry updated')}catch(e){toast(e.message,true)}}
async function convertInquiry3(id){try{const i=A.state.inquiries.find(x=>x.id===id);let p=A.state.projects.find(x=>x.inquiry_id===id);if(!p)p=await A.insertRow('projects',{customer_id:i.customer_id,inquiry_id:i.id,name:i.event_name||'Event project',status:'planning',brand:'Rachna + Aavartan',date_range_bs:i.event_date_bs||null});const a=bs2ad(i.event_date_bs);if(!p.id)throw Error('Project was not created');await A.insertRow('event_functions',{project_id:p.id,name:i.event_name||'Event',event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:i.event_date_bs||null,venue:i.venue||null,guest_count:i.guest_count||null});await A.editRow('inquiries',id,{status:'awaiting_advance'});openProject(p.id);toast('Project created')}catch(e){toast(e.message||'Conversion failed',true)}}
function newProject3(){modal('New project',sel('Customer','pc',[['','Select customer…'],...A.state.customers.map(c=>[c.id,c.name])])+fld('Project name','pn')+sel('Brand','pb',[['Rachna + Aavartan','Rachna + Aavartan'],['Aavartan','Aavartan'],['Rachna','Rachna']],'Rachna + Aavartan')+fld('First function','pfn','text','Wedding')+bsField('First function date','pd')+fld('Venue','pv')+fld('Guests','pg','number'),'<button class="btn primary" onclick="saveProject3()">Create project</button>');setTimeout(()=>window.__date3('pd'),0)}
async function saveProject3(){try{const p=await A.insertRow('projects',{customer_id:$('#pc').value||null,name:$('#pn').value.trim(),status:'planning',brand:$('#pb').value,date_range_bs:$('#pdBS').value});const a=bs2ad($('#pdBS').value);await A.insertRow('event_functions',{project_id:p.id,name:$('#pfn').value.trim()||'Wedding',event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#pdBS').value,venue:$('#pv').value.trim()||null,guest_count:+$('#pg').value||null});close();openProject(p.id);toast('Project saved')}catch(e){toast(e.message||'Project save failed',true)}}
function editProject3(id){const p=A.state.projects.find(x=>x.id===id);modal('Edit project',fld('Project name','epn','text',p.name)+sel('Brand','epb',[['Rachna + Aavartan','Rachna + Aavartan'],['Aavartan','Aavartan'],['Rachna','Rachna']],p.brand)+sel('Status','eps',[['planning','Planning'],['in_progress','In progress'],['completed','Completed'],['booked','Booked']],p.status),`<button class="btn primary" onclick="saveProjectEdit3('${id}')">Save</button>`)}
async function saveProjectEdit3(id){try{await A.editRow('projects',id,{name:$('#epn').value.trim(),brand:$('#epb').value,status:$('#eps').value});close();render();toast('Project updated')}catch(e){toast(e.message,true)}}
async function deleteProject3(id){if(!confirm('Delete project and all attached records?'))return;try{const qids=A.state.quotations.filter(x=>x.project_id===id).map(x=>x.id);const child=[['quotation_items',x=>qids.includes(x.quotation_id)],['quotations',x=>x.project_id===id],['project_team',x=>x.project_id===id],['vendor_bookings',x=>x.project_id===id],['project_services',x=>x.project_id===id],['production_costs',x=>x.project_id===id],['aavartan_deliverables',x=>x.project_id===id],['tasks',x=>x.project_id===id],['payments',x=>x.project_id===id],['project_expenses',x=>x.project_id===id],['documents',x=>x.project_id===id],['event_functions',x=>x.project_id===id]];for(const [t,f] of child){for(const x of (A.state[t]||[]).filter(f))await A.deleteRow(t,x.id)}await A.deleteRow('projects',id);go('projects');toast('Project deleted')}catch(e){toast(e.message||'Delete failed',true)}}
function newFunction3(pid){const p=A.state.projects.find(x=>x.id===pid);modal('Add function',fld('Function name','fn')+bsField('Function date','fd',p?.date_range_bs||'')+fld('Venue','fv')+fld('Guests','fg','number')+fld('Start time','ft','time')+area('Notes','fnotes'),`<button class="btn primary" onclick="saveFunction3('${pid}')">Save</button>`);setTimeout(()=>window.__date3('fd'),0)}
async function saveFunction3(pid){try{const a=bs2ad($('#fdBS').value);await A.insertRow('event_functions',{project_id:pid,name:$('#fn').value.trim(),event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#fdBS').value,venue:$('#fv').value.trim()||null,guest_count:+$('#fg').value||null,start_time:$('#ft').value||null,notes:$('#fnotes').value.trim()||null});close();render();toast('Function saved')}catch(e){toast(e.message,true)}}
function editFunction3(id){const f=A.state.functions.find(x=>x.id===id);modal('Edit function',fld('Function name','efn','text',f.name)+bsField('Function date','efd',f.event_date_bs)+fld('Venue','efv','text',f.venue||'')+fld('Guests','efg','number',f.guest_count||'')+fld('Start time','eft','time',f.start_time||'')+area('Notes','efn0',f.notes||''),`<button class="btn primary" onclick="saveFunctionEdit3('${id}')">Save</button>`);setTimeout(()=>window.__date3('efd'),0)}
async function saveFunctionEdit3(id){try{const a=bs2ad($('#efdBS').value);await A.editRow('event_functions',id,{name:$('#efn').value.trim(),event_date:a?`${a.year}-${String(a.month).padStart(2,'0')}-${String(a.date).padStart(2,'0')}`:null,event_date_bs:$('#efdBS').value,venue:$('#efv').value.trim()||null,guest_count:+$('#efg').value||null,start_time:$('#eft').value||null,notes:$('#efn0').value.trim()||null});close();render();toast('Function updated')}catch(e){toast(e.message,true)}}
function quickFunction3(){A.state.projects.length?newFunction3(A.state.projects[0].id):newProject3()}
function servicePicker3(pid){const names=A.state.projectServices.filter(x=>x.project_id===pid).map(x=>x.name);let body=`<div class="service-group"><div class="group-title">Aavartan · CORE</div><label class="checkline"><input id="sc" type="checkbox" ${names.includes(CORE[0])?'checked':''}><span><b>${CORE[0]}</b><small>Photography + videography together · ${money(CORE[1])}</small></span></label></div><div class="service-group"><div class="group-title">Aavartan · ADD-ONS</div><div class="check-grid">${ADDONS.map(x=>`<label class="checkline"><input class="ao" type="checkbox" value="${esc(x[0])}" ${names.includes(x[0])?'checked':''}><span><b>${esc(x[0])}</b><small>${money(x[1])}</small></span></label>`).join('')}</div></div><div class="service-group"><div class="group-title">Rachna · EVENT MANAGEMENT</div><div class="check-grid">${RACHNA.map(x=>`<label class="checkline"><input class="ro" type="checkbox" value="${esc(x)}" ${names.includes(x)?'checked':''}><span><b>${esc(x)}</b><small>Price set in quote</small></span></label>`).join('')}</div></div>`;modal('Choose services',body,`<button class="btn primary" onclick="saveServices3('${pid}')">Save selection</button>`)}
async function saveServices3(pid){try{for(const x of A.state.projectServices.filter(x=>x.project_id===pid))await A.deleteRow('project_services',x.id);const jobs=[];if($('#sc')?.checked)jobs.push(A.insertRow('project_services',{project_id:pid,name:CORE[0],customer_price:CORE[1],internal_cost:0,quantity:1}));document.querySelectorAll('.ao:checked').forEach(e=>{const x=ADDONS.find(a=>a[0]===e.value);jobs.push(A.insertRow('project_services',{project_id:pid,name:x[0],customer_price:x[1],internal_cost:0,quantity:1}))});document.querySelectorAll('.ro:checked').forEach(e=>jobs.push(A.insertRow('project_services',{project_id:pid,name:e.value,customer_price:0,internal_cost:0,quantity:1})));await Promise.all(jobs);await A.recalc(pid);close();render();toast('Services saved')}catch(e){toast(e.message||'Services save failed',true)}}
function editPS3(id){const x=A.state.projectServices.find(s=>s.id===id);modal('Edit service',fld('Name','psn','text',x.name)+fld('Customer price','psp','number',x.customer_price)+fld('Internal cost','psi','number',x.internal_cost)+fld('Quantity','psq','number',x.quantity||1),`<button class="btn primary" onclick="savePS3('${id}')">Save</button>`)}
async function savePS3(id){try{const x=A.state.projectServices.find(s=>s.id===id);await A.editRow('project_services',id,{name:$('#psn').value.trim(),customer_price:+$('#psp').value||0,internal_cost:+$('#psi').value||0,quantity:+$('#psq').value||1});await A.recalc(x.project_id);close();render();toast('Service updated')}catch(e){toast(e.message,true)}}
async function delPS3(id,pid){await del3('project_services',id);await A.recalc(pid);render()}
async function newQuote3(pid){try{const r=await A.sb.from('quotations').select('version').eq('project_id',pid).order('version',{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;await A.insertRow('quotations',{project_id:pid,version:(r.data?.version||0)+1,status:'draft',customer_total:0,internal_total:0,notes:null});await A.recalc(pid);render();toast('Quotation created')}catch(e){toast(e.message,true)}}
function quote3(id){const q=A.state.quotations.find(x=>x.id===id),it=A.state.quotationItems.filter(x=>x.quotation_id===id);modal('Quotation v'+q.version,`<div class="grid two-col"><div class="card inner"><b>Total</b><div class="big-number">${money(q.customer_total)}</div></div><div class="card inner"><b>Status</b><div class="big-number">${esc(ST[q.status]||q.status)}</div></div></div>${table(['Description','Qty','Price',''],it.map(x=>`<tr><td>${esc(x.description)}</td><td>${esc(x.quantity)}</td><td>${money(x.customer_price)}</td><td class="row-actions"><button class="btn tiny" onclick="editQI3('${x.id}','${q.project_id}')">Edit</button><button class="btn tiny danger" onclick="del3('quotation_items','${x.id}')">Delete</button></td></tr>`))}`,`<button class="btn primary" onclick="newQI3('${id}','${q.project_id}')">Add line</button>`)}
function newQI3(qid,pid){modal('Add quote line',fld('Description','qid')+fld('Quantity','qiq','number','1')+fld('Customer price','qip','number','0')+fld('Internal cost','qii','number','0'),`<button class="btn primary" onclick="saveQI3('${qid}','${pid}')">Save</button>`)}
async function saveQI3(qid,pid){try{await A.insertRow('quotation_items',{quotation_id:qid,description:$('#qid').value.trim(),quantity:+$('#qiq').value||1,customer_price:+$('#qip').value||0,internal_cost:+$('#qii').value||0});await A.recalc(pid);close();render();toast('Quote line saved')}catch(e){toast(e.message,true)}}
function editQI3(id,pid){const x=A.state.quotationItems.find(i=>i.id===id);modal('Edit quote line',fld('Description','eqd','text',x.description)+fld('Quantity','eqq','number',x.quantity||1)+fld('Customer price','eqp','number',x.customer_price)+fld('Internal cost','eqi','number',x.internal_cost),`<button class="btn primary" onclick="saveQIEdit3('${id}','${pid}')">Save</button>`)}
async function saveQIEdit3(id,pid){try{await A.editRow('quotation_items',id,{description:$('#eqd').value.trim(),quantity:+$('#eqq').value||1,customer_price:+$('#eqp').value||0,internal_cost:+$('#eqi').value||0});await A.recalc(pid);close();render();toast('Quote line updated')}catch(e){toast(e.message,true)}}
function advance3(pid){const p=A.state.projects.find(x=>x.id===pid),need=Number(p.quoted_total||0)*.3;modal('Customer advance',fld('Amount received now','adv','number','','min="1"')+`<div class="advance-rule"><b>30% booking rule</b><div>Required: ${money(need)}</div><div>Received: ${money(p.customer_advance)}</div></div>`+fld('Method','avm')+fld('Reference','avr'),`<button class="btn primary" onclick="saveAdvance3('${pid}')">Save</button>`)}
async function saveAdvance3(pid){try{const n=+$('#adv').value;if(!(n>0))throw Error('Enter valid amount');const r=await A.recordAdvance(pid,n,$('#avm').value,$('#avr').value);close();render();toast(r.booked?'Booking confirmed':'Advance recorded')}catch(e){toast(e.message||'Advance save failed',true)}}
function newVendorBooking3(pid){modal('Vendor booking',sel('Vendor','vbv',[['','Select vendor…'],...A.state.vendors.map(v=>[v.id,v.name])])+sel('Function','vbf',[['','General'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+fld('Quoted cost','vbc','number','0')+fld('Advance paid','vba','number','0')+fld('Final paid','vbfp','number','0'),`<button class="btn primary" onclick="saveVB3('${pid}')">Save</button>`)}
async function saveVB3(pid){try{await A.insertRow('vendor_bookings',{project_id:pid,vendor_id:$('#vbv').value,function_id:$('#vbf').value||null,quoted_cost:+$('#vbc').value||0,advance_paid:+$('#vba').value||0,final_paid:+$('#vbfp').value||0,status:'confirmed'});await A.recalc(pid);close();render();toast('Vendor saved')}catch(e){toast(e.message,true)}}
function editVB3(id){const x=A.state.vendorBookings.find(v=>v.id===id);modal('Edit vendor booking',fld('Quoted cost','evc','number',x.quoted_cost)+fld('Advance paid','eva','number',x.advance_paid)+fld('Final paid','evf','number',x.final_paid)+sel('Status','evs',[['confirmed','Confirmed'],['pending','Pending'],['paid','Paid']],x.status),`<button class="btn primary" onclick="saveVBEdit3('${id}')">Save</button>`)}
async function saveVBEdit3(id){try{const x=A.state.vendorBookings.find(v=>v.id===id);await A.editRow('vendor_bookings',id,{quoted_cost:+$('#evc').value||0,advance_paid:+$('#eva').value||0,final_paid:+$('#evf').value||0,status:$('#evs').value});await A.recalc(x.project_id);close();render();toast('Vendor updated')}catch(e){toast(e.message,true)}}
function assignTeam3(pid){modal('Assign team',sel('Team member','tm',[['','Select…'],...A.state.team.filter(x=>x.active!==false).map(x=>[x.id,x.name+' · '+(x.role||'')])])+sel('Function','tmf',[['','General'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+fld('Rate','tmr','number','0')+area('Responsibility','tmres'),`<button class="btn primary" onclick="saveTeam3('${pid}')">Assign</button>`)}
async function saveTeam3(pid){try{await A.insertRow('project_team',{project_id:pid,team_member_id:$('#tm').value,function_id:$('#tmf').value||null,rate:+$('#tmr').value||0,responsibility:$('#tmres').value.trim()||null});await A.recalc(pid);close();render();toast('Team assigned')}catch(e){toast(e.message,true)}}
function newCost3(pid){modal('Production cost',sel('Function','pcf',[['','General'],...A.state.functions.filter(f=>f.project_id===pid).map(f=>[f.id,f.name])])+fld('Category','pcc','text','Photography / Video')+fld('Description','pcd')+fld('Quantity','pcq','number','1')+fld('Unit cost','pcu','number','0'),`<button class="btn primary" onclick="saveCost3('${pid}')">Save</button>`)}
async function saveCost3(pid){try{await A.insertRow('production_costs',{project_id:pid,function_id:$('#pcf').value||null,brand:'Aavartan',category:$('#pcc').value,description:$('#pcd').value.trim(),quantity:+$('#pcq').value||1,unit_cost:+$('#pcu').value||0});await A.recalc(pid);close();render();toast('Cost saved')}catch(e){toast(e.message,true)}}
function editCost3(id){const x=A.state.productionCosts.find(c=>c.id===id);modal('Edit production cost',fld('Description','ecd','text',x.description)+fld('Category','ecc','text',x.category||'Other')+fld('Quantity','ecq','number',x.quantity||1)+fld('Unit cost','ecu','number',x.unit_cost||0),`<button class="btn primary" onclick="saveCostEdit3('${id}')">Save</button>`)}
async function saveCostEdit3(id){try{const x=A.state.productionCosts.find(c=>c.id===id);await A.editRow('production_costs',id,{description:$('#ecd').value.trim(),category:$('#ecc').value,quantity:+$('#ecq').value||1,unit_cost:+$('#ecu').value||0});await A.recalc(x.project_id);close();render();toast('Cost updated')}catch(e){toast(e.message,true)}}
function paymentModal3(pid){modal('Payment',sel('Direction','pd',[['in','Customer received'],['out','Paid out']],'in')+fld('Amount','pa','number','','min="1"')+fld('Date','pdt','date',new Date().toISOString().slice(0,10))+fld('Method','pm')+fld('Reference','pr')+area('Notes','pn'),`<button class="btn primary" onclick="savePay3('${pid}')">Save</button>`)}
function projectPayment3(pid){paymentModal3(pid)}function globalPayment3(){A.state.projects.length?paymentModal3(A.state.projects[0].id):toast('Create a project first',true)}
async function savePay3(pid){try{await A.insertRow('payments',{project_id:pid,direction:$('#pd').value,party_type:'other',amount:+$('#pa').value,payment_date:$('#pdt').value,method:$('#pm').value||null,reference:$('#pr').value||null,notes:$('#pn').value||null});close();render();toast('Payment saved')}catch(e){toast(e.message,true)}}
function editPayment3(id){const x=A.state.payments.find(p=>p.id===id);modal('Edit payment',sel('Direction','epd',[['in','Customer received'],['out','Paid out']],x.direction)+fld('Amount','epa','number',x.amount)+fld('Date','epdt','date',x.payment_date)+fld('Method','epm','text',x.method||'')+fld('Reference','epr','text',x.reference||'')+area('Notes','epn',x.notes||''),`<button class="btn primary" onclick="savePayEdit3('${id}')">Save</button>`)}
async function savePayEdit3(id){try{await A.editRow('payments',id,{direction:$('#epd').value,amount:+$('#epa').value,payment_date:$('#epdt').value,method:$('#epm').value||null,reference:$('#epr').value||null,notes:$('#epn').value||null});close();render();toast('Payment updated')}catch(e){toast(e.message,true)}}
function newDelivery3(pid){modal('Deliverable',fld('Deliverable','dn')+fld('Due date','dd','date')+sel('Status','dst',[['pending','Pending'],['in_progress','In progress'],['delivered','Delivered']]),`<button class="btn primary" onclick="saveDelivery3('${pid}')">Save</button>`)}
async function saveDelivery3(pid){try{await A.insertRow('aavartan_deliverables',{project_id:pid,deliverable:$('#dn').value.trim(),due_date:$('#dd').value||null,status:$('#dst').value});close();render();toast('Deliverable saved')}catch(e){toast(e.message,true)}}
function editDelivery3(id){const x=A.state.deliverables.find(d=>d.id===id);modal('Edit deliverable',fld('Deliverable','edn','text',x.deliverable)+fld('Due date','edd','date',x.due_date||'')+sel('Status','eds',[['pending','Pending'],['in_progress','In progress'],['delivered','Delivered']],x.status),`<button class="btn primary" onclick="saveDeliveryEdit3('${id}')">Save</button>`)}
async function saveDeliveryEdit3(id){try{await A.editRow('aavartan_deliverables',id,{deliverable:$('#edn').value.trim(),due_date:$('#edd').value||null,status:$('#eds').value});close();render();toast('Deliverable updated')}catch(e){toast(e.message,true)}}
async function del3(t,id){if(!confirm('Delete this record?'))return;try{await A.deleteRow(t,id);render();toast('Deleted')}catch(e){toast(e.message||'Delete failed',true)}}window.del3=del3;
function customerManager3(){modal('Customers',table(['Name','Phone','Email',''],A.state.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone||'')}</td><td>${esc(c.email||'')}</td><td class="row-actions"><button class="btn tiny" onclick="editCustomer3('${c.id}')">Edit</button><button class="btn tiny danger" onclick="del3('customers','${c.id}')">Delete</button></td></tr>`)),`<button class="btn primary" onclick="newCustomer3()">New customer</button>`)}
function newCustomer3(){modal('New customer',fld('Name','cn')+fld('Phone','cp','tel')+fld('WhatsApp','cw','tel')+fld('Email','ce','email')+area('Notes','cno'),'<button class="btn primary" onclick="saveCustomer3()">Save</button>')}
async function saveCustomer3(){try{await A.insertRow('customers',{name:$('#cn').value.trim(),phone:$('#cp').value.trim()||null,whatsapp:$('#cw').value.trim()||$('#cp').value.trim()||null,email:$('#ce').value.trim()||null,notes:$('#cno').value.trim()||null});customerManager3();toast('Customer saved')}catch(e){toast(e.message,true)}}
function editCustomer3(id){const c=A.state.customers.find(x=>x.id===id);modal('Edit customer',fld('Name','ecn','text',c.name)+fld('Phone','ecp','tel',c.phone||'')+fld('WhatsApp','ecw','tel',c.whatsapp||'')+fld('Email','ece','email',c.email||'')+area('Notes','ecno',c.notes||''),`<button class="btn primary" onclick="saveCustomerEdit3('${id}')">Save</button>`)}
async function saveCustomerEdit3(id){try{await A.editRow('customers',id,{name:$('#ecn').value.trim(),phone:$('#ecp').value.trim()||null,whatsapp:$('#ecw').value.trim()||null,email:$('#ece').value.trim()||null,notes:$('#ecno').value.trim()||null});close();render();toast('Customer updated')}catch(e){toast(e.message,true)}}
function vendorManager3(){modal('Vendors',table(['Name','Category','Area','Phone',''],A.state.vendors.map(v=>`<tr><td>${esc(v.name)}</td><td>${esc(v.service_category||'')}</td><td>${esc(v.area||'')}</td><td>${esc(v.phone||'')}</td><td class="row-actions"><button class="btn tiny" onclick="editVendor3('${v.id}')">Edit</button><button class="btn tiny danger" onclick="del3('vendors','${v.id}')">Delete</button></td></tr>`)),`<button class="btn primary" onclick="newVendor3()">New vendor</button>`)}
function newVendor3(){modal('New vendor',fld('Name','vn')+fld('Phone','vp','tel')+fld('Category','vc')+fld('Area','va')+fld('Rate guide','vr')+sel('Reliability','vrel',['Low','Medium','High'],'Medium')+area('Notes','vno'),'<button class="btn primary" onclick="saveVendor3()">Save</button>')}
async function saveVendor3(){try{await A.insertRow('vendors',{name:$('#vn').value.trim(),phone:$('#vp').value.trim()||null,service_category:$('#vc').value.trim()||null,area:$('#va').value.trim()||null,rate_guide:$('#vr').value.trim()||null,reliability:$('#vrel').value,notes:$('#vno').value.trim()||null});vendorManager3();toast('Vendor saved')}catch(e){toast(e.message,true)}}
function editVendor3(id){const v=A.state.vendors.find(x=>x.id===id);modal('Edit vendor',fld('Name','evn','text',v.name)+fld('Phone','evp','tel',v.phone||'')+fld('Category','evc','text',v.service_category||'')+fld('Area','eva','text',v.area||'')+fld('Rate guide','evr','text',v.rate_guide||'')+sel('Reliability','evrel',['Low','Medium','High'],v.reliability||'Medium')+area('Notes','evno',v.notes||''),`<button class="btn primary" onclick="saveVendorEdit3('${id}')">Save</button>`)}
async function saveVendorEdit3(id){try{await A.editRow('vendors',id,{name:$('#evn').value.trim(),phone:$('#evp').value.trim()||null,service_category:$('#evc').value.trim()||null,area:$('#eva').value.trim()||null,rate_guide:$('#evr').value.trim()||null,reliability:$('#evrel').value,notes:$('#evno').value.trim()||null});close();render();toast('Vendor updated')}catch(e){toast(e.message,true)}}
function teamManager3(){modal('Team',table(['Name','Role','Phone','Active',''],A.state.team.map(t=>`<tr><td>${esc(t.name)}</td><td>${esc(t.role||'')}</td><td>${esc(t.phone||'')}</td><td>${t.active===false?'No':'Yes'}</td><td class="row-actions"><button class="btn tiny" onclick="editTeam3('${t.id}')">Edit</button><button class="btn tiny danger" onclick="del3('team_members','${t.id}')">Delete</button></td></tr>`)),`<button class="btn primary" onclick="newTeam3()">New member</button>`)}
function newTeam3(){modal('New team member',fld('Name','tn')+fld('Role','tro')+fld('Phone','tp','tel')+fld('Email','te','email')+sel('Active','ta',[['true','Yes'],['false','No']],'true'),'<button class="btn primary" onclick="saveTeamMember3()">Save</button>')}
async function saveTeamMember3(){try{await A.insertRow('team_members',{name:$('#tn').value.trim(),role:$('#tro').value.trim()||null,phone:$('#tp').value.trim()||null,email:$('#te').value.trim()||null,active:$('#ta').value==='true'});teamManager3();toast('Team member saved')}catch(e){toast(e.message,true)}}
function editTeam3(id){const t=A.state.team.find(x=>x.id===id);modal('Edit team member',fld('Name','etn','text',t.name)+fld('Role','etro','text',t.role||'')+fld('Phone','etp','tel',t.phone||'')+fld('Email','ete','email',t.email||'')+sel('Active','eta',[['true','Yes'],['false','No']],t.active===false?'false':'true'),`<button class="btn primary" onclick="saveTeamEdit3('${id}')">Save</button>`)}
async function saveTeamEdit3(id){try{await A.editRow('team_members',id,{name:$('#etn').value.trim(),role:$('#etro').value.trim()||null,phone:$('#etp').value.trim()||null,email:$('#ete').value.trim()||null,active:$('#eta').value==='true'});close();render();toast('Team updated')}catch(e){toast(e.message,true)}}
function serviceManager3(){modal('Service catalog',table(['Brand','Name','Category','Base','Internal',''],A.state.services.map(s=>`<tr><td>${esc(s.brand)}</td><td>${esc(s.name)}</td><td>${esc(s.category||'')}</td><td>${money(s.base_price)}</td><td>${money(s.internal_cost)}</td><td class="row-actions"><button class="btn tiny" onclick="editCatalog3('${s.id}')">Edit</button><button class="btn tiny danger" onclick="del3('services','${s.id}')">Delete</button></td></tr>`)),`<button class="btn primary" onclick="newCatalog3()">New service</button>`)}
function newCatalog3(){modal('New service',sel('Brand','sb',['Rachna','Aavartan'])+fld('Name','sn')+fld('Category','scat')+fld('Base price','sbp','number','0')+fld('Internal cost','sic','number','0')+sel('Active','sa',[['true','Yes'],['false','No']],'true'),'<button class="btn primary" onclick="saveCatalog3()">Save</button>')}
async function saveCatalog3(){try{await A.insertRow('services',{brand:$('#sb').value,name:$('#sn').value.trim(),category:$('#scat').value.trim()||null,base_price:+$('#sbp').value||0,internal_cost:+$('#sic').value||0,active:$('#sa').value==='true'});serviceManager3();toast('Service saved')}catch(e){toast(e.message,true)}}
function editCatalog3(id){const s=A.state.services.find(x=>x.id===id);modal('Edit service',sel('Brand','esb',['Rachna','Aavartan'],s.brand)+fld('Name','esn','text',s.name)+fld('Category','esc','text',s.category||'')+fld('Base price','esp','number',s.base_price)+fld('Internal cost','esi','number',s.internal_cost)+sel('Active','esa',[['true','Yes'],['false','No']],s.active===false?'false':'true'),`<button class="btn primary" onclick="saveCatalogEdit3('${id}')">Save</button>`)}
async function saveCatalogEdit3(id){try{await A.editRow('services',id,{brand:$('#esb').value,name:$('#esn').value.trim(),category:$('#esc').value.trim()||null,base_price:+$('#esp').value||0,internal_cost:+$('#esi').value||0,active:$('#esa').value==='true'});close();render();toast('Service updated')}catch(e){toast(e.message,true)}}
function account3(){if(A.state.user)modal('Account',`<div class="detail-grid"><div><span>Name</span><b>${esc(A.state.profile?.full_name||'Owner')}</b></div><div><span>Email</span><b>${esc(A.state.user.email||'')}</b></div></div>`,'<button class="btn primary" onclick="A.signOut()">Sign out</button>');else toast('Please sign in',true)}
Object.assign(window,{newInquiry3,saveInquiry3,editInquiry3,saveInquiryEdit3,convertInquiry3,newProject3,saveProject3,editProject3,saveProjectEdit3,deleteProject3,newFunction3,saveFunction3,editFunction3,saveFunctionEdit3,quickFunction3,servicePicker3,saveServices3,editPS3,savePS3,delPS3,newQuote3,quote3,newQI3,saveQI3,editQI3,saveQIEdit3,advance3,saveAdvance3,newVendorBooking3,saveVB3,editVB3,saveVBEdit3,assignTeam3,saveTeam3,newCost3,saveCost3,editCost3,saveCostEdit3,paymentModal3,projectPayment3,globalPayment3,savePay3,editPayment3,savePayEdit3,newDelivery3,saveDelivery3,editDelivery3,saveDeliveryEdit3,customerManager3,newCustomer3,saveCustomer3,editCustomer3,saveCustomerEdit3,vendorManager3,newVendor3,saveVendor3,editVendor3,saveVendorEdit3,teamManager3,newTeam3,saveTeamMember3,editTeam3,saveTeamEdit3,serviceManager3,newCatalog3,saveCatalog3,editCatalog3,saveCatalogEdit3,account3});
if($('#nav')){$('#nav').innerHTML=nav.map(n=>`<button class="nav-item" data-page="${n[0]}" onclick="go('${n[0]}')"><span class="nav-dot"></span>${n[1]}</button>`).join('');$('#refresh').onclick=()=>A.refresh().then(()=>{render();toast('Data refreshed')}).catch(e=>toast(e.message,true));$('#authBtn').onclick=account3;$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')close()}}
render();
})();