(()=>{
const A=window.RachnaAPI;
const $=s=>document.querySelector(s);
const E=A.esc;
const sources=['Instagram','Facebook','WhatsApp','Referral','Website','Phone','Walk-in','Other'];
const months=['Baisakh','Jestha','Ashadh','Shrawan','Bhadra','Ashwin','Kartik','Mangsir','Poush','Magh','Falgun','Chaitra'];
const MD={2075:[31,31,32,31,31,31,30,29,30,29,30,30],2076:[31,32,31,32,31,30,30,30,29,29,30,30],2077:[31,32,31,32,31,30,30,30,29,30,29,31],2078:[31,31,31,32,31,31,30,29,30,29,30,30],2079:[31,31,32,31,31,31,30,29,30,29,30,30],2080:[31,32,31,32,31,30,30,30,29,29,30,30],2081:[31,31,32,32,31,30,30,29,30,30,30,30],2082:[30,32,31,32,31,30,30,29,30,30,30,30],2083:[31,31,32,31,31,30,30,29,30,30,30,30],2084:[31,31,32,31,31,30,30,29,30,30,30,30],2085:[31,32,31,32,30,31,30,30,29,30,30,30],2086:[30,32,31,32,31,30,30,29,30,30,30,30],2087:[31,31,32,31,31,31,30,30,29,30,30,30],2088:[30,31,32,32,30,31,30,30,29,30,30,30],2089:[30,32,31,32,31,30,30,30,29,30,30,30],2090:[30,32,31,32,31,30,30,30,29,30,30,30],2091:[31,31,32,31,31,31,30,30,29,30,30,30],2092:[30,31,32,32,31,30,30,30,29,30,30,30],2093:[30,32,31,32,31,30,30,30,30,29,30,30],2094:[31,31,32,31,31,30,30,30,30,30,30,30],2095:[31,31,32,31,31,31,30,29,30,30,30,30],2096:[30,31,32,32,31,30,30,29,30,29,30,30],2097:[31,32,31,32,31,30,30,29,30,30,30,30],2098:[31,31,32,31,31,31,29,30,29,30,29,31],2099:[31,31,32,31,31,31,30,29,29,30,30,30]};
function closeModal(){const b=$('#backdrop');if(b)b.classList.remove('show')}
function toast(msg,error=false){const t=$('#toast');if(!t)return;t.textContent=msg;t.className='toast show '+(error?'error':'');clearTimeout(window.__fix5toast);window.__fix5toast=setTimeout(()=>t.className='toast',3000)}
function field(label,id,type='text',value='',extra=''){return '<div class="field"><label>'+label+'</label><input id="'+id+'" type="'+type+'" value="'+E(value)+'" '+extra+'></div>'}
function select(label,id,options,value=''){return '<div class="field"><label>'+label+'</label><select id="'+id+'">'+options.map(o=>{const a=Array.isArray(o)?o:[o,o];return '<option value="'+E(a[0])+'" '+(String(a[0])===String(value)?'selected':'')+'>'+E(a[1])+'</option>'}).join('')+'</select></div>'}
function textarea(label,id,value=''){return '<div class="field full"><label>'+label+'</label><textarea id="'+id+'">'+E(value)+'</textarea></div>'}
function todayBS(){try{return new DateConverter(new Date().toISOString().slice(0,10)).toBs()}catch{return {year:2083,month:1,date:1}}}
function datePicker(k,value=''){let p=todayBS();if(/^\d{4}-\d{2}-\d{2}$/.test(value)){const a=value.split('-').map(Number);p={year:a[0],month:a[1],date:a[2]}}const n=(MD[p.year]||MD[2083])[p.month-1]||30;const d=Math.min(p.date,n);let ys='';for(let y=2075;y<=2099;y++)ys+='<option value="'+y+'" '+(y===p.year?'selected':'')+'>'+y+'</option>';return '<div class="field full"><label>Event date · BS</label><div class="date-grid"><select id="'+k+'Y" onchange="fix5SyncDate(\''+k+'\')">'+ys+'</select><select id="'+k+'M" onchange="fix5SyncDate(\''+k+'\')">'+months.map((m,i)=>'<option value="'+(i+1)+'" '+(i+1===p.month?'selected':'')+'>'+m+'</option>').join('')+'</select><select id="'+k+'D">'+Array.from({length:n},(_,i)=>i+1).map(x=>'<option value="'+x+'" '+(x===d?'selected':'')+'>'+x+'</option>').join('')+'</select></div><input type="hidden" id="'+k+'BS" value="'+p.year+'-'+String(p.month).padStart(2,'0')+'-'+String(d).padStart(2,'0')+'"><div id="'+k+'AD" class="date-preview"></div></div>'}
window.fix5SyncDate=function(k){const y=+$('#'+k+'Y').value,m=+$('#'+k+'M').value,max=(MD[y]||MD[2083])[m-1]||30,old=+$('#'+k+'D').value||1,d=Math.min(old,max);$('#'+k+'D').innerHTML=Array.from({length:max},(_,i)=>i+1).map(x=>'<option value="'+x+'" '+(x===d?'selected':'')+'>'+x+'</option>').join('');const bs=y+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');$('#'+k+'BS').value=bs;try{const a=new DateConverter(bs).toAd();$('#'+k+'AD').textContent='AD '+String(a.date).padStart(2,'0')+' '+a.month+' '+a.year}catch{$('#'+k+'AD').textContent=''}};
window.newInquiry=function(){
 if(!A.state.user){ toast('Please sign in first.',true); if(typeof window.auth==='function')window.auth(); return; }
 const body='<div class="grid two-col">'+field('Customer name *','inqCustomer')+field('Phone / WhatsApp','inqPhone','text','','autocomplete="tel"')+field('Email','inqEmail','email')+select('Lead source','inqSource',sources,'Instagram')+field('Event / wedding name *','inqEvent')+field('Guest count','inqGuests','number','')+datePicker('inqDate')+field('Venue','inqVenue')+field('Budget','inqBudget','number')+textarea('Notes','inqNotes')+'</div>';
 const actions='<button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="fix5SaveInquiry()">Create inquiry</button>';
 const modalEl=$('#modal');modalEl.innerHTML='<div class="modal-head"><div><div class="eyebrow">Sales</div><h2>New inquiry</h2></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body">'+body+'</div><div class="modal-foot">'+actions+'</div>';
 $('#backdrop').classList.add('show');
 setTimeout(()=>fix5SyncDate('inqDate'),0);
};
window.fix5SaveInquiry=async function(){try{const x={customer_name:$('#inqCustomer').value.trim(),phone:$('#inqPhone').value.trim(),email:$('#inqEmail').value.trim(),source:$('#inqSource').value,event_name:$('#inqEvent').value.trim(),guest_count:$('#inqGuests').value,budget:$('#inqBudget').value,event_date_bs:$('#inqDateBS').value,venue:$('#inqVenue').value.trim(),notes:$('#inqNotes').value.trim()};if(!x.customer_name||!x.event_name)throw Error('Customer name and event name are required');await A.createInquiry(x);closeModal();toast('Inquiry created');if(typeof window.render==='function')window.render();else location.reload();}catch(e){toast(e.message||'Could not create inquiry',true)}};
window.openI=async function(id){const i=A.state.inquiries.find(x=>x.id===id);if(!i)return;const c=A.state.customers.find(x=>x.id===i.customer_id);const body='<div class="detail-grid"><div><span>Customer</span><b>'+E(c?.name||'—')+'</b></div><div><span>Phone</span><b>'+E(c?.phone||'—')+'</b></div><div><span>Event</span><b>'+E(i.event_name||'—')+'</b></div><div><span>Date</span><b>'+E(i.event_date_bs||'Date TBC')+'</b></div><div><span>Venue</span><b>'+E(i.venue||'Venue TBC')+'</b></div><div><span>Guests</span><b>'+E(i.guest_count||'—')+'</b></div></div><div class="field full"><label>Status</label><select id="inqStatus">'+['new','contacted','qualified','quote_sent','negotiation','awaiting_advance','lost'].map(v=>'<option value="'+v+'" '+(v===i.status?'selected':'')+'>'+v.replace(/_/g,' ')+'</option>').join('')+'</select></div><div class="field full"><label>Notes</label><textarea id="inqEditNotes">'+E(i.notes||'')+'</textarea></div>';
 const actions='<button class="btn" onclick="closeModal()">Close</button><button class="btn" onclick="fix5UpdateInquiry(\''+id+'\')">Save</button><button class="btn primary" onclick="fix5Convert(\''+id+'\')">Convert to project</button>';
 $('#modal').innerHTML='<div class="modal-head"><div><div class="eyebrow">Sales</div><h2>Inquiry</h2></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="modal-body">'+body+'</div><div class="modal-foot">'+actions+'</div>';$('#backdrop').classList.add('show');};
window.fix5UpdateInquiry=async function(id){try{await A.update('inquiries',id,{status:$('#inqStatus').value,notes:$('#inqEditNotes').value.trim(),updated_at:new Date().toISOString()});closeModal();toast('Inquiry updated');if(typeof window.render==='function')window.render();}catch(e){toast(e.message,true)}};
window.fix5Convert=async function(id){try{const p=await A.convertInquiry(id);closeModal();toast('Project created');window.openP&&window.openP(p.id);}catch(e){toast(e.message,true)}};
window.paymentGlobal=window.paymentGlobal||function(){toast('Open a project to record project-linked payment.',true)};
window.globalPayment=window.globalPayment||window.paymentGlobal;
})();